export const adminTranslations = {
  ar: {
    brand: { centralAdministration: "الإدارة المركزية", systemAdmin: "مسؤول النظام" },
    nav: {
      administration: "الإدارة", system: "النظام", dashboard: "لوحة التحكم", users: "المستخدمون", investors: "المستثمرون", projects: "المشاريع", investments: "الاستثمارات", requests: "الطلبات", messages: "الرسائل", documents: "الوثائق", settings: "الإعدادات", publicSite: "الموقع العام", logout: "تسجيل الخروج", openMenu: "فتح القائمة", closeMenu: "إغلاق القائمة"
    },
    topbar: { agency: "الوكالة الجزائرية لترقية الاستثمار", search: "اكتب هنا للبحث...", searchAria: "بحث الإدارة", notifications: "الإشعارات" },
    dashboard: {
      eyebrow: "AAPI / ADMINISTRATION", title: "لوحة التحكم", subtitle: "نظرة شاملة وفورية على نشاط الوكالة والاستثمار.", refresh: "تحديث البيانات", refreshing: "جاري التحديث", retry: "إعادة المحاولة", projectsTotal: "إجمالي المشاريع", investors: "المستثمرون", investmentValue: "قيمة الاستثمارات", jobs: "مناصب العمل", projectActivity: "نشاط المشاريع", registeredUsers: "المستخدمون المسجلون", totalValue: "القيمة الإجمالية", jobOpportunities: "فرص العمل", analytics: "التحليلات", investmentActivity: "نشاط الاستثمارات", activityGrowth: "نمو النشاط", overview: "نظرة عامة", projectSummary: "ملخص المشاريع", approvedProjects: "المشاريع المقبولة", activeProjects: "المشاريع النشطة", investmentStatus: "حالة الاستثمارات", pending: "في الانتظار", approved: "مقبولة", active: "قيد التنفيذ", completed: "منتهية", cancelled: "ملغاة", systemStatus: "حالة الوكالة", validDocuments: "الوثائق السليمة", recentActivity: "النشاط الأخير", recentProjects: "آخر المشاريع", projectsCount: "مشاريع", project: "المشروع", investor: "المستثمر", wilaya: "الولاية", status: "الحالة", value: "القيمة", noMatchingProjects: "لا توجد مشاريع مطابقة.", activity: "العمليات", recentOperations: "آخر العمليات", newProject: "مشروع جديد", days: "يوم", now: "الآن", defaultWilaya: "الجزائر", projectStatuses: { brouillon: "مسودة", soumis: "مُرسل", en_etude: "قيد الدراسة", approuve: "مقبول", en_cours: "قيد التنفيذ", realise: "منجز", rejete: "مرفوض", archive: "مؤرشف" }
    }
  },
  fr: {
    brand: { centralAdministration: "Administration centrale", systemAdmin: "Administrateur système" },
    nav: {
      administration: "Administration", system: "Système", dashboard: "Tableau de bord", users: "Utilisateurs", investors: "Investisseurs", projects: "Projets", investments: "Investissements", requests: "Demandes", messages: "Messages", documents: "Documents", settings: "Paramètres", publicSite: "Site public", logout: "Déconnexion", openMenu: "Ouvrir le menu", closeMenu: "Fermer le menu"
    },
    topbar: { agency: "Agence Algérienne de Promotion de l’Investissement", search: "Rechercher ici...", searchAria: "Recherche administration", notifications: "Notifications" },
    dashboard: {
      eyebrow: "AAPI / ADMINISTRATION", title: "Tableau de bord", subtitle: "Une vue globale et en temps réel de l’activité de l’agence et de l’investissement.", refresh: "Actualiser les données", refreshing: "Actualisation...", retry: "Réessayer", projectsTotal: "Total des projets", investors: "Investisseurs", investmentValue: "Valeur des investissements", jobs: "Emplois", projectActivity: "Activité des projets", registeredUsers: "Utilisateurs inscrits", totalValue: "Valeur totale", jobOpportunities: "Opportunités d’emploi", analytics: "ANALYTIQUE", investmentActivity: "Activité des investissements", activityGrowth: "Croissance de l’activité", overview: "VUE D’ENSEMBLE", projectSummary: "Résumé des projets", approvedProjects: "Projets approuvés", activeProjects: "Projets actifs", investmentStatus: "État des investissements", pending: "En attente", approved: "Validés", active: "En cours", completed: "Terminés", cancelled: "Annulés", systemStatus: "État du système", validDocuments: "Documents conformes", recentActivity: "ACTIVITÉ RÉCENTE", recentProjects: "Projets récents", projectsCount: "projets", project: "Projet", investor: "Investisseur", wilaya: "Wilaya", status: "Statut", value: "Valeur", noMatchingProjects: "Aucun projet correspondant.", activity: "ACTIVITÉ", recentOperations: "Dernières opérations", newProject: "Nouveau projet", days: "jour", now: "À l’instant", defaultWilaya: "Alger", projectStatuses: { brouillon: "Brouillon", soumis: "Soumis", en_etude: "À l’étude", approuve: "Approuvé", en_cours: "En cours", realise: "Réalisé", rejete: "Rejeté", archive: "Archivé" }
    }
  },
  en: {
    brand: { centralAdministration: "Central Administration", systemAdmin: "System Administrator" },
    nav: {
      administration: "Administration", system: "System", dashboard: "Dashboard", users: "Users", investors: "Investors", projects: "Projects", investments: "Investments", requests: "Requests", messages: "Messages", documents: "Documents", settings: "Settings", publicSite: "Public website", logout: "Sign out", openMenu: "Open menu", closeMenu: "Close menu"
    },
    topbar: { agency: "Algerian Agency for Investment Promotion", search: "Search here...", searchAria: "Administration search", notifications: "Notifications" },
    dashboard: {
      eyebrow: "AAPI / ADMINISTRATION", title: "Dashboard", subtitle: "A comprehensive, real-time view of agency and investment activity.", refresh: "Refresh data", refreshing: "Refreshing...", retry: "Try again", projectsTotal: "Total projects", investors: "Investors", investmentValue: "Investment value", jobs: "Jobs", projectActivity: "Project activity", registeredUsers: "Registered users", totalValue: "Total value", jobOpportunities: "Job opportunities", analytics: "ANALYTICS", investmentActivity: "Investment activity", activityGrowth: "Activity growth", overview: "OVERVIEW", projectSummary: "Project summary", approvedProjects: "Approved projects", activeProjects: "Active projects", investmentStatus: "Investment status", pending: "Pending", approved: "Approved", active: "In progress", completed: "Completed", cancelled: "Cancelled", systemStatus: "SYSTEM STATUS", validDocuments: "Valid documents", recentActivity: "RECENT ACTIVITY", recentProjects: "Recent projects", projectsCount: "projects", project: "Project", investor: "Investor", wilaya: "Wilaya", status: "Status", value: "Value", noMatchingProjects: "No matching projects.", activity: "ACTIVITY", recentOperations: "Recent operations", newProject: "New project", days: "day", now: "Now", defaultWilaya: "Algiers", projectStatuses: { brouillon: "Draft", soumis: "Submitted", en_etude: "Under review", approuve: "Approved", en_cours: "In progress", realise: "Completed", rejete: "Rejected", archive: "Archived" }
    }
  }
} as const;
