export const adminTranslations = {
  ar: {
    common: { language: "اللغة" },
    brand: { centralAdministration: "الإدارة المركزية", systemAdmin: "مسؤول النظام" },
    nav: {
      administration: "الإدارة", system: "النظام", dashboard: "لوحة التحكم", users: "المستخدمون", investors: "المستثمرون", projects: "المشاريع", investments: "الاستثمارات", requests: "الطلبات", messages: "الرسائل", documents: "الوثائق", announcements: "الإعلانات", settings: "الإعدادات", publicSite: "الموقع العام", logout: "تسجيل الخروج", openMenu: "فتح القائمة", closeMenu: "إغلاق القائمة"
    },
    topbar: { agency: "الوكالة الجزائرية لترقية الاستثمار", search: "اكتب هنا للبحث...", searchAria: "بحث الإدارة", notifications: "الإشعارات" },
    dashboard: {
      eyebrow: "AAPI / ADMINISTRATION", title: "لوحة التحكم", subtitle: "نظرة شاملة وفورية على نشاط الوكالة والاستثمار.", refresh: "تحديث البيانات", refreshing: "جاري التحديث", retry: "إعادة المحاولة", projectsTotal: "إجمالي المشاريع", investors: "المستثمرون", investmentValue: "قيمة الاستثمارات", jobs: "مناصب العمل", projectActivity: "نشاط المشاريع", registeredUsers: "المستخدمون المسجلون", totalValue: "القيمة الإجمالية", jobOpportunities: "فرص العمل", analytics: "التحليلات", investmentActivity: "نشاط الاستثمارات", activityGrowth: "نمو النشاط", overview: "نظرة عامة", projectSummary: "ملخص المشاريع", approvedProjects: "المشاريع المقبولة", activeProjects: "المشاريع النشطة", investmentStatus: "حالة الاستثمارات", pending: "في الانتظار", approved: "مقبولة", active: "قيد التنفيذ", completed: "منتهية", cancelled: "ملغاة", systemStatus: "حالة الوكالة", validDocuments: "الوثائق السليمة", recentActivity: "النشاط الأخير", recentProjects: "آخر المشاريع", projectsCount: "مشاريع", project: "المشروع", investor: "المستثمر", wilaya: "الولاية", status: "الحالة", value: "القيمة", noMatchingProjects: "لا توجد مشاريع مطابقة.", activity: "العمليات", recentOperations: "آخر العمليات", newProject: "مشروع جديد", days: "يوم", now: "الآن", defaultWilaya: "الجزائر", projectStatuses: { brouillon: "مسودة", soumis: "مُرسل", en_etude: "قيد الدراسة", approuve: "مقبول", en_cours: "قيد التنفيذ", realise: "منجز", rejete: "مرفوض", archive: "مؤرشف" }
    },
    data: {
      section: {
        users: { title: "المستخدمون", subtitle: "إدارة حسابات مستخدمي المنصة" },
        investors: { title: "المستثمرون", subtitle: "إدارة ملفات المستثمرين" },
        projects: { title: "المشاريع", subtitle: "متابعة ومراجعة مشاريع الاستثمار" },
        investments: { title: "الاستثمارات", subtitle: "متابعة عمليات الاستثمار" },
        requests: { title: "الطلبات", subtitle: "متابعة طلبات المستثمرين وتحديث حالتها" },
        messages: { title: "الرسائل", subtitle: "إدارة رسائل المستثمرين ومتابعة المقروء وغير المقروء" },
        documents: { title: "الوثائق", subtitle: "مراجعة وثائق المستثمرين والتحقق من حالتها" },
        announcements: { title: "الإعلانات", subtitle: "إنشاء ونشر ومتابعة إعلانات الوكالة" }
      },
      labels: {
        id: "المعرف", user_id: "معرف المستخدم", investor_id: "معرف المستثمر", investisseur_id: "معرف المستثمر", nom: "الاسم", prenom: "اللقب", email: "البريد الإلكتروني", telephone: "الهاتف", role: "الدور", titre: "المشروع", nom_projet: "المشروع", wilaya: "الولاية", secteur: "القطاع", statut: "الحالة", montant: "المبلغ", montant_investissement: "قيمة الاستثمار", montant_effectif: "المبلغ الفعلي", date_creation: "تاريخ الإنشاء", created_at: "تاريخ الإنشاء", updated_at: "آخر تحديث", date_publication: "تاريخ النشر", auteur_id: "معرف الكاتب", image: "الصورة", message: "الرسالة", sujet: "الموضوع", lu: "القراءة", document: "الوثيقة", type: "النوع", description: "الوصف", utilisateur_id: "معرف المستخدم", brouillon: "مسودة", soumis: "مُرسل", en_etude: "قيد الدراسة", approuve: "مقبول", en_cours: "قيد التنفيذ", realise: "منجز", rejete: "مرفوض", archive: "مؤرشف", actif: "نشط", inactif: "غير نشط", suspendu: "موقوف", en_attente: "في الانتظار", valide: "مقبول", termine: "منتهي", annule: "ملغى", nouvelle: "جديد", acceptee: "مقبول", refusee: "مرفوض", terminee: "منتهٍ", non_lu: "غير مقروء"
      },
      totalRecords: "إجمالي السجلات", activeAccepted: "نشطة / مقبولة", pending: "قيد المتابعة", rejectedStopped: "مرفوضة / متوقفة", liveUpdate: "AAPI • تحديث مباشر", dataManagement: "إدارة البيانات", items: "عنصر", search: "ابحث في البيانات...", searchAria: "بحث", allStatuses: "كل الحالات", reset: "إعادة ضبط", refresh: "تحديث البيانات", loading: "جاري تحميل البيانات...", noData: "لا توجد بيانات مطابقة.", action: "الإجراء", reading: "القراءة", markRead: "تعيين كمقروء", markUnread: "تعيين كغير مقروء", updateStatus: "تحديث الحالة", unknownError: "حدث خطأ", loadError: "تعذر تحميل البيانات", updateError: "تعذر تحديث الحالة", messageError: "تعذر تحديث الرسالة", read: "مقروء", unread: "غير مقروء", announcement: { new: "إضافة إعلان جديد", eyebrow: "AAPI • الإعلانات", description: "أنشئ إعلاناً رسمياً وسيظهر في الموقع العام حسب حالة النشر.", title: "العنوان", titlePlaceholder: "عنوان الإعلان", content: "المحتوى", contentPlaceholder: "اكتب محتوى الإعلان هنا...", status: "حالة النشر", published: "منشور", draft: "مسودة", archived: "مؤرشف", image: "رابط الصورة", imagePlaceholder: "https://...", publicationDate: "تاريخ النشر", publish: "إضافة الإعلان", publishing: "جاري النشر..." }
    },
    settings: {
      eyebrow: "AAPI / SYSTEM", title: "الإعدادات", subtitle: "إدارة معلومات حساب المسؤول ومظهر لوحة الإدارة.", account: "معلومات الحساب", accountSubtitle: "تعديل المعلومات الشخصية الظاهرة في حساب المسؤول.", firstName: "الاسم", lastName: "اللقب", email: "البريد الإلكتروني", phone: "رقم الهاتف", role: "الدور", accountStatus: "حالة الحساب", admin: "مسؤول النظام", active: "نشط", save: "حفظ معلومات الحساب", saved: "تم الحفظ", appearance: "مظهر لوحة التحكم", appearanceSubtitle: "اختر الوضع الذي تريد استخدامه. سيتم حفظ اختيارك تلقائياً.", dark: "الوضع الداكن", light: "الوضع الفاتح", current: "الوضع الحالي", openMenu: "فتح قائمة الإدارة", closeMenu: "إغلاق القائمة"
    }
  },
  fr: {
    common: { language: "Langue" },
    brand: { centralAdministration: "Administration centrale", systemAdmin: "Administrateur système" },
    nav: {
      administration: "Administration", system: "Système", dashboard: "Tableau de bord", users: "Utilisateurs", investors: "Investisseurs", projects: "Projets", investments: "Investissements", requests: "Demandes", messages: "Messages", documents: "Documents", announcements: "Annonces", settings: "Paramètres", publicSite: "Site public", logout: "Déconnexion", openMenu: "Ouvrir le menu", closeMenu: "Fermer le menu"
    },
    topbar: { agency: "Agence Algérienne de Promotion de l’Investissement", search: "Rechercher ici...", searchAria: "Recherche administration", notifications: "Notifications" },
    dashboard: {
      eyebrow: "AAPI / ADMINISTRATION", title: "Tableau de bord", subtitle: "Une vue globale et en temps réel de l’activité de l’agence et de l’investissement.", refresh: "Actualiser les données", refreshing: "Actualisation...", retry: "Réessayer", projectsTotal: "Total des projets", investors: "Investisseurs", investmentValue: "Valeur des investissements", jobs: "Emplois", projectActivity: "Activité des projets", registeredUsers: "Utilisateurs inscrits", totalValue: "Valeur totale", jobOpportunities: "Opportunités d’emploi", analytics: "ANALYTIQUE", investmentActivity: "Activité des investissements", activityGrowth: "Croissance de l’activité", overview: "VUE D’ENSEMBLE", projectSummary: "Résumé des projets", approvedProjects: "Projets approuvés", activeProjects: "Projets actifs", investmentStatus: "État des investissements", pending: "En attente", approved: "Validés", active: "En cours", completed: "Terminés", cancelled: "Annulés", systemStatus: "État du système", validDocuments: "Documents conformes", recentActivity: "ACTIVITÉ RÉCENTE", recentProjects: "Projets récents", projectsCount: "projets", project: "Projet", investor: "Investisseur", wilaya: "Wilaya", status: "Statut", value: "Valeur", noMatchingProjects: "Aucun projet correspondant.", activity: "ACTIVITÉ", recentOperations: "Dernières opérations", newProject: "Nouveau projet", days: "jour", now: "À l’instant", defaultWilaya: "Alger", projectStatuses: { brouillon: "Brouillon", soumis: "Soumis", en_etude: "À l’étude", approuve: "Approuvé", en_cours: "En cours", realise: "Réalisé", rejete: "Rejeté", archive: "Archivé" }
    },
    data: {
      section: {
        users: { title: "Utilisateurs", subtitle: "Gérer les comptes des utilisateurs de la plateforme" },
        investors: { title: "Investisseurs", subtitle: "Gérer les dossiers des investisseurs" },
        projects: { title: "Projets", subtitle: "Suivre et examiner les projets d’investissement" },
        investments: { title: "Investissements", subtitle: "Suivre les opérations d’investissement" },
        requests: { title: "Demandes", subtitle: "Suivre les demandes des investisseurs et mettre à jour leur statut" },
        messages: { title: "Messages", subtitle: "Gérer les messages des investisseurs et suivre les messages lus et non lus" },
        documents: { title: "Documents", subtitle: "Examiner les documents des investisseurs et vérifier leur statut" },
        announcements: { title: "Annonces", subtitle: "Créer, publier et suivre les annonces de l’agence" }
      },
      labels: {
        id: "Identifiant", user_id: "ID utilisateur", investor_id: "ID investisseur", investisseur_id: "ID investisseur", nom: "Nom", prenom: "Prénom", email: "E-mail", telephone: "Téléphone", role: "Rôle", titre: "Projet", nom_projet: "Projet", wilaya: "Wilaya", secteur: "Secteur", statut: "Statut", montant: "Montant", montant_investissement: "Valeur de l’investissement", montant_effectif: "Montant effectif", date_creation: "Date de création", created_at: "Date de création", updated_at: "Dernière mise à jour", date_publication: "Date de publication", auteur_id: "ID auteur", image: "Image", message: "Message", sujet: "Objet", lu: "Lecture", document: "Document", type: "Type", description: "Description", utilisateur_id: "ID utilisateur", brouillon: "Brouillon", soumis: "Soumis", en_etude: "À l’étude", approuve: "Approuvé", en_cours: "En cours", realise: "Réalisé", rejete: "Rejeté", archive: "Archivé", actif: "Actif", inactif: "Inactif", suspendu: "Suspendu", en_attente: "En attente", valide: "Validé", termine: "Terminé", annule: "Annulé", nouvelle: "Nouveau", acceptee: "Acceptée", refusee: "Refusée", terminee: "Terminée", non_lu: "Non lu"
      },
      totalRecords: "Total des enregistrements", activeAccepted: "Actifs / validés", pending: "En cours de suivi", rejectedStopped: "Rejetés / suspendus", liveUpdate: "AAPI • Mise à jour en direct", dataManagement: "GESTION DES DONNÉES", items: "éléments", search: "Rechercher dans les données...", searchAria: "Recherche", allStatuses: "Tous les statuts", reset: "Réinitialiser", refresh: "Actualiser les données", loading: "Chargement des données...", noData: "Aucune donnée correspondante.", action: "Action", reading: "Lecture", markRead: "Marquer comme lu", markUnread: "Marquer comme non lu", updateStatus: "Mettre à jour le statut", unknownError: "Une erreur est survenue", loadError: "Impossible de charger les données", updateError: "Impossible de mettre à jour le statut", messageError: "Impossible de mettre à jour le message", read: "Lu", unread: "Non lu", announcement: { new: "Nouvelle annonce", eyebrow: "AAPI • ANNONCES", description: "Créez une annonce officielle qui sera affichée sur le site public selon son statut.", title: "Titre", titlePlaceholder: "Titre de l’annonce", content: "Contenu", contentPlaceholder: "Rédigez le contenu de l’annonce...", status: "Statut de publication", published: "Publiée", draft: "Brouillon", archived: "Archivée", image: "URL de l’image", imagePlaceholder: "https://...", publicationDate: "Date de publication", publish: "Ajouter l’annonce", publishing: "Publication..." }
    },
    settings: {
      eyebrow: "AAPI / SYSTÈME", title: "Paramètres", subtitle: "Gérer les informations du compte administrateur et l’apparence du panneau d’administration.", account: "Informations du compte", accountSubtitle: "Modifier les informations personnelles affichées dans le compte administrateur.", firstName: "Prénom", lastName: "Nom", email: "E-mail", phone: "Téléphone", role: "Rôle", accountStatus: "État du compte", admin: "Administrateur", active: "Actif", save: "Enregistrer les informations", saved: "Enregistré", appearance: "Apparence du tableau de bord", appearanceSubtitle: "Choisissez le mode à utiliser. Votre choix sera enregistré automatiquement.", dark: "Mode sombre", light: "Mode clair", current: "Mode actuel", openMenu: "Ouvrir le menu d’administration", closeMenu: "Fermer le menu"
    }
  },
  en: {
    common: { language: "Language" },
    brand: { centralAdministration: "Central Administration", systemAdmin: "System Administrator" },
    nav: {
      administration: "Administration", system: "System", dashboard: "Dashboard", users: "Users", investors: "Investors", projects: "Projects", investments: "Investments", requests: "Requests", messages: "Messages", documents: "Documents", announcements: "Announcements", settings: "Settings", publicSite: "Public website", logout: "Sign out", openMenu: "Open menu", closeMenu: "Close menu"
    },
    topbar: { agency: "Algerian Agency for Investment Promotion", search: "Search here...", searchAria: "Administration search", notifications: "Notifications" },
    dashboard: {
      eyebrow: "AAPI / ADMINISTRATION", title: "Dashboard", subtitle: "A comprehensive, real-time view of agency and investment activity.", refresh: "Refresh data", refreshing: "Refreshing...", retry: "Try again", projectsTotal: "Total projects", investors: "Investors", investmentValue: "Investment value", jobs: "Jobs", projectActivity: "Project activity", registeredUsers: "Registered users", totalValue: "Total value", jobOpportunities: "Job opportunities", analytics: "ANALYTICS", investmentActivity: "Investment activity", activityGrowth: "Activity growth", overview: "OVERVIEW", projectSummary: "Project summary", approvedProjects: "Approved projects", activeProjects: "Active projects", investmentStatus: "Investment status", pending: "Pending", approved: "Approved", active: "In progress", completed: "Completed", cancelled: "Cancelled", systemStatus: "SYSTEM STATUS", validDocuments: "Valid documents", recentActivity: "RECENT ACTIVITY", recentProjects: "Recent projects", projectsCount: "projects", project: "Project", investor: "Investor", wilaya: "Wilaya", status: "Status", value: "Value", noMatchingProjects: "No matching projects.", activity: "ACTIVITY", recentOperations: "Recent operations", newProject: "New project", days: "day", now: "Now", defaultWilaya: "Algiers", projectStatuses: { brouillon: "Draft", soumis: "Submitted", en_etude: "Under review", approuve: "Approved", en_cours: "In progress", realise: "Completed", rejete: "Rejected", archive: "Archived" }
    },
    data: {
      section: {
        users: { title: "Users", subtitle: "Manage platform user accounts" },
        investors: { title: "Investors", subtitle: "Manage investor profiles" },
        projects: { title: "Projects", subtitle: "Review and monitor investment projects" },
        investments: { title: "Investments", subtitle: "Monitor investment operations" },
        requests: { title: "Requests", subtitle: "Monitor investor requests and update their status" },
        messages: { title: "Messages", subtitle: "Manage investor messages and track read and unread messages" },
        documents: { title: "Documents", subtitle: "Review investor documents and verify their status" },
        announcements: { title: "Announcements", subtitle: "Create, publish and manage agency announcements" }
      },
      labels: {
        id: "ID", user_id: "User ID", investor_id: "Investor ID", investisseur_id: "Investor ID", nom: "Last name", prenom: "First name", email: "Email", telephone: "Phone", role: "Role", titre: "Project", nom_projet: "Project", wilaya: "Wilaya", secteur: "Sector", statut: "Status", montant: "Amount", montant_investissement: "Investment value", montant_effectif: "Effective amount", date_creation: "Creation date", created_at: "Creation date", updated_at: "Last updated", date_publication: "Publication date", auteur_id: "Author ID", image: "Image", message: "Message", sujet: "Subject", lu: "Read status", document: "Document", type: "Type", description: "Description", utilisateur_id: "User ID", brouillon: "Draft", soumis: "Submitted", en_etude: "Under review", approuve: "Approved", en_cours: "In progress", realise: "Completed", rejete: "Rejected", archive: "Archived", actif: "Active", inactif: "Inactive", suspendu: "Suspended", en_attente: "Pending", valide: "Validated", termine: "Completed", annule: "Cancelled", nouvelle: "New", acceptee: "Accepted", refusee: "Rejected", terminee: "Completed", non_lu: "Unread"
      },
      totalRecords: "Total records", activeAccepted: "Active / accepted", pending: "Pending review", rejectedStopped: "Rejected / suspended", liveUpdate: "AAPI • Live update", dataManagement: "DATA MANAGEMENT", items: "items", search: "Search data...", searchAria: "Search", allStatuses: "All statuses", reset: "Reset", refresh: "Refresh data", loading: "Loading data...", noData: "No matching data.", action: "Action", reading: "Read status", markRead: "Mark as read", markUnread: "Mark as unread", updateStatus: "Update status", unknownError: "An error occurred", loadError: "Unable to load data", updateError: "Unable to update status", messageError: "Unable to update message", read: "Read", unread: "Unread", announcement: { new: "New announcement", eyebrow: "AAPI • ANNOUNCEMENTS", description: "Create an official announcement that will appear on the public website according to its publication status.", title: "Title", titlePlaceholder: "Announcement title", content: "Content", contentPlaceholder: "Write the announcement content here...", status: "Publication status", published: "Published", draft: "Draft", archived: "Archived", image: "Image URL", imagePlaceholder: "https://...", publicationDate: "Publication date", publish: "Add announcement", publishing: "Publishing..." }
    },
    settings: {
      eyebrow: "AAPI / SYSTEM", title: "Settings", subtitle: "Manage administrator account information and the administration panel appearance.", account: "Account information", accountSubtitle: "Edit the personal information displayed in the administrator account.", firstName: "First name", lastName: "Last name", email: "Email", phone: "Phone number", role: "Role", accountStatus: "Account status", admin: "Administrator", active: "Active", save: "Save account information", saved: "Saved", appearance: "Dashboard appearance", appearanceSubtitle: "Choose the mode you want to use. Your choice will be saved automatically.", dark: "Dark mode", light: "Light mode", current: "Current mode", openMenu: "Open administration menu", closeMenu: "Close menu"
    }
  }
} as const;
