export const announcementsDetailsTranslations = {
  ar: { page:{notFound:"الإعلان غير موجود",notFoundText:"عذرًا، لم نتمكن من العثور على الإعلان الذي تبحث عنه.",back:"العودة إلى الإعلانات",media:"الإعلانات",title:"تفاصيل الإعلان",home:"الرئيسية",details:"التفاصيل",important:"إعلان مهم",backList:"العودة إلى قائمة الإعلانات",print:"طباعة الإعلان",all:"الإعلانات",allText:"تابع آخر الإعلانات والمعلومات المتعلقة بالمستثمرين والمشاريع الاستثمارية.",allLink:"جميع الإعلانات",opportunities:"فرص الاستثمار",opportunitiesText:"اكتشف الفرص الاستثمارية المتاحة حسب القطاعات والمجالات الاقتصادية.",opportunitiesLink:"اكتشف الفرص",help:"هل تحتاج إلى مساعدة؟",helpText:"تواصل معنا للحصول على المزيد من المعلومات.",contact:"اتصل بنا"}, articles:{
    "1":{title:"فتح باب استقبال طلبات الاستفادة من فرص الاستثمار",category:"إعلانات المستثمرين",date:"02 سبتمبر 2026",excerpt:"إعلان لفائدة المستثمرين الراغبين في الاطلاع على الفرص الاستثمارية المتاحة.",content:["تعلن الوكالة عن فتح باب استقبال طلبات المستثمرين الراغبين في الاستفادة من المعلومات المتعلقة بفرص الاستثمار المتاحة.","يمكن للمستثمرين الاطلاع على المشاريع والفرص حسب القطاعات والنشاطات الاقتصادية المختلفة.","يتم استقبال الطلبات ودراستها وفق الإجراءات المعمول بها."]},
    "2":{title:"إعلان عن تحديث بعض الإجراءات المتعلقة بالمشاريع الاستثمارية",category:"إعلانات عامة",date:"30 أوت 2026",excerpt:"تحديث المعلومات المتعلقة بمراحل تسجيل ومتابعة المشاريع الاستثمارية.",content:["تم تحديث المعلومات الخاصة ببعض الإجراءات المرتبطة بالمشاريع الاستثمارية.","ينصح المستثمرون بالاطلاع على آخر المعلومات قبل إيداع ملفاتهم.","تهدف هذه التحديثات إلى تحسين وضوح المسار الاستثماري وتسهيل الإجراءات."]},
    "3":{title:"دعوة للمشاركة في لقاء حول فرص الاستثمار",category:"مواعيد",date:"27 أوت 2026",excerpt:"لقاء إعلامي موجه للمستثمرين حول الفرص المتاحة وآليات المرافقة.",content:["تنظم الوكالة لقاءً إعلاميًا لفائدة المستثمرين والمتعاملين الاقتصاديين.","يتناول اللقاء مختلف فرص الاستثمار وآليات المرافقة المتاحة للمستثمر.","يمكن للراغبين في المشاركة متابعة الإعلانات الرسمية الخاصة باللقاء."]},
    "4":{title:"عرض مشاريع استثمارية جديدة في عدة قطاعات",category:"طلبات وعروض",date:"24 أوت 2026",excerpt:"مجموعة من الفرص والمشاريع الاستثمارية المقترحة أمام المستثمرين.",content:["تم عرض مجموعة من المشاريع الاستثمارية الجديدة في عدة قطاعات اقتصادية.","تتوفر معلومات أولية حول طبيعة المشاريع ومواقعها ومجالات نشاطها.","يمكن للمستثمرين المهتمين التواصل مع المصالح المختصة للحصول على مزيد من المعلومات."]},
    "5":{title:"إعلان لفائدة حاملي المشاريع الاستثمارية",category:"إعلانات المستثمرين",date:"20 أوت 2026",excerpt:"معلومات وتوجيهات جديدة لفائدة حاملي المشاريع الراغبين في الاستثمار.",content:["يخص هذا الإعلان حاملي المشاريع الاستثمارية الراغبين في إطلاق مشاريع جديدة.","يمكن الاستفادة من خدمات المرافقة والتوجيه للحصول على المعلومات اللازمة.","ندعو حاملي المشاريع إلى تحضير ملفاتهم والاطلاع على مختلف مراحل المسار الاستثماري."]},
    "6":{title:"إطلاق خدمة معلوماتية جديدة للمستثمرين",category:"إعلانات عامة",date:"16 أوت 2026",excerpt:"خدمة جديدة تهدف إلى تسهيل الوصول إلى المعلومات الاستثمارية.",content:["تم إطلاق خدمة معلوماتية جديدة تهدف إلى تحسين تجربة المستثمر.","توفر الخدمة إمكانية الوصول بشكل أسرع إلى المعلومات الأساسية المتعلقة بالاستثمار.","سيتم تطوير الخدمة وإثراؤها تدريجيًا بإمكانيات إضافية."]},
    "7":{title:"إعلان حول آجال إيداع بعض الملفات",category:"مواعيد",date:"12 أوت 2026",excerpt:"تذكير بالمواعيد والآجال المتعلقة بإيداع بعض الملفات والطلبات.",content:["تذكر الوكالة المستثمرين بضرورة احترام الآجال المحددة لإيداع الملفات.","ينصح بالتأكد من استكمال الوثائق المطلوبة قبل إيداع أي ملف.","للاستفسارات يمكن استعمال قنوات الاتصال المتاحة عبر الموقع."]},
    "8":{title:"دعوة للاطلاع على الفرص الاستثمارية حسب القطاعات",category:"طلبات وعروض",date:"08 أوت 2026",excerpt:"اكتشف مجموعة من القطاعات والفرص الاستثمارية المتاحة.",content:["تدعو الوكالة المستثمرين إلى الاطلاع على الفرص الاستثمارية المصنفة حسب القطاعات.","تشمل الفرص مجالات اقتصادية متعددة يمكن للمستثمرين دراستها وفق احتياجاتهم.","للمزيد من المعلومات يمكن الانتقال إلى فضاء فرص الاستثمار."]}
  }},
  fr: { page:{notFound:"Annonce introuvable",notFoundText:"Désolé, nous n'avons pas trouvé l'annonce recherchée.",back:"Retour aux annonces",media:"Annonces",title:"Détails de l'annonce",home:"Accueil",details:"Détails",important:"Annonce importante",backList:"Retour à la liste des annonces",print:"Imprimer l'annonce",all:"Annonces",allText:"Suivez les dernières annonces et informations concernant les investisseurs et les projets d'investissement.",allLink:"Toutes les annonces",opportunities:"Opportunités d'investissement",opportunitiesText:"Découvrez les opportunités d'investissement disponibles par secteur et domaine économique.",opportunitiesLink:"Découvrir les opportunités",help:"Besoin d'aide ?",helpText:"Contactez-nous pour obtenir plus d'informations.",contact:"Nous contacter"}, articles:{
    "1":{title:"Ouverture de la réception des demandes relatives aux opportunités d'investissement",category:"Annonces investisseurs",date:"02 septembre 2026",excerpt:"Annonce destinée aux investisseurs souhaitant découvrir les opportunités d'investissement disponibles.",content:["L'agence annonce l'ouverture de la réception des demandes des investisseurs souhaitant obtenir des informations sur les opportunités disponibles.","Les investisseurs peuvent consulter les projets et opportunités par secteurs et activités économiques.","Les demandes sont reçues et étudiées conformément aux procédures en vigueur."]},
    "2":{title:"Mise à jour de certaines procédures relatives aux projets d'investissement",category:"Annonces générales",date:"30 août 2026",excerpt:"Mise à jour des informations relatives à l'enregistrement et au suivi des projets d'investissement.",content:["Les informations relatives à certaines procédures liées aux projets d'investissement ont été mises à jour.","Les investisseurs sont invités à consulter les dernières informations avant de déposer leurs dossiers.","Ces mises à jour visent à clarifier le parcours d'investissement et à faciliter les procédures."]},
    "3":{title:"Invitation à une rencontre sur les opportunités d'investissement",category:"Dates",date:"27 août 2026",excerpt:"Rencontre d'information destinée aux investisseurs sur les opportunités et les mécanismes d'accompagnement.",content:["L'agence organise une rencontre d'information destinée aux investisseurs et opérateurs économiques.","La rencontre porte sur les opportunités d'investissement et les mécanismes d'accompagnement disponibles.","Les personnes intéressées peuvent suivre les annonces officielles relatives à la rencontre."]},
    "4":{title:"Présentation de nouveaux projets d'investissement dans plusieurs secteurs",category:"Demandes et offres",date:"24 août 2026",excerpt:"Un ensemble d'opportunités et de projets d'investissement proposés aux investisseurs.",content:["Un ensemble de nouveaux projets d'investissement a été présenté dans plusieurs secteurs économiques.","Des informations préliminaires sont disponibles sur la nature, les sites et les domaines d'activité des projets.","Les investisseurs intéressés peuvent contacter les services compétents pour plus d'informations."]},
    "5":{title:"Annonce destinée aux porteurs de projets d'investissement",category:"Annonces investisseurs",date:"20 août 2026",excerpt:"Nouvelles informations et orientations pour les porteurs de projets souhaitant investir.",content:["Cette annonce concerne les porteurs de projets souhaitant lancer de nouveaux investissements.","Ils peuvent bénéficier des services d'accompagnement et d'orientation pour obtenir les informations nécessaires.","Les porteurs de projets sont invités à préparer leurs dossiers et à consulter les différentes étapes du parcours d'investissement."]},
    "6":{title:"Lancement d'un nouveau service d'information pour les investisseurs",category:"Annonces générales",date:"16 août 2026",excerpt:"Un nouveau service destiné à faciliter l'accès aux informations d'investissement.",content:["Un nouveau service d'information a été lancé afin d'améliorer l'expérience des investisseurs.","Le service permet un accès plus rapide aux informations essentielles liées à l'investissement.","Le service sera progressivement développé et enrichi de nouvelles fonctionnalités."]},
    "7":{title:"Annonce concernant les délais de dépôt de certains dossiers",category:"Dates",date:"12 août 2026",excerpt:"Rappel des dates et délais relatifs au dépôt de certains dossiers et demandes.",content:["L'agence rappelle aux investisseurs la nécessité de respecter les délais fixés pour le dépôt des dossiers.","Il est recommandé de vérifier que les documents requis sont complets avant tout dépôt.","Pour toute question, les canaux de contact disponibles sur le site peuvent être utilisés."]},
    "8":{title:"Invitation à consulter les opportunités d'investissement par secteur",category:"Demandes et offres",date:"08 août 2026",excerpt:"Découvrez un ensemble de secteurs et d'opportunités d'investissement disponibles.",content:["L'agence invite les investisseurs à consulter les opportunités d'investissement classées par secteur.","Les opportunités couvrent plusieurs domaines économiques que les investisseurs peuvent étudier selon leurs besoins.","Pour plus d'informations, consultez l'espace dédié aux opportunités d'investissement."]}
  }},
  en: { page:{notFound:"Announcement not found",notFoundText:"Sorry, we could not find the announcement you are looking for.",back:"Back to announcements",media:"Announcements",title:"Announcement details",home:"Home",details:"Details",important:"Important announcement",backList:"Back to announcements list",print:"Print announcement",all:"Announcements",allText:"Follow the latest announcements and information for investors and investment projects.",allLink:"All announcements",opportunities:"Investment opportunities",opportunitiesText:"Discover investment opportunities by sector and economic field.",opportunitiesLink:"Discover opportunities",help:"Need help?",helpText:"Contact us for more information.",contact:"Contact us"}, articles:{
    "1":{title:"Opening of applications for investment opportunities",category:"Investor announcements",date:"02 September 2026",excerpt:"An announcement for investors interested in discovering available investment opportunities.",content:["The agency announces the opening of applications from investors seeking information about available investment opportunities.","Investors can explore projects and opportunities by sector and economic activity.","Applications are received and reviewed in accordance with applicable procedures."]},
    "2":{title:"Update of certain procedures related to investment projects",category:"General announcements",date:"30 August 2026",excerpt:"Updated information concerning the registration and monitoring of investment projects.",content:["Information on certain procedures related to investment projects has been updated.","Investors are advised to review the latest information before submitting their files.","These updates aim to clarify the investment journey and facilitate procedures."]},
    "3":{title:"Invitation to a meeting on investment opportunities",category:"Dates",date:"27 August 2026",excerpt:"An information meeting for investors on available opportunities and support mechanisms.",content:["The agency is organizing an information meeting for investors and economic operators.","The meeting will address investment opportunities and support mechanisms available to investors.","Interested participants can follow the official announcements related to the meeting."]},
    "4":{title:"Presentation of new investment projects across several sectors",category:"Requests and offers",date:"24 August 2026",excerpt:"A selection of investment opportunities and projects presented to investors.",content:["A selection of new investment projects has been presented across several economic sectors.","Initial information is available on the nature, locations and fields of activity of the projects.","Interested investors can contact the relevant services for more information."]},
    "5":{title:"Announcement for investment project owners",category:"Investor announcements",date:"20 August 2026",excerpt:"New information and guidance for project owners wishing to invest.",content:["This announcement concerns project owners wishing to launch new investments.","They can benefit from support and guidance services to obtain the necessary information.","Project owners are invited to prepare their files and review the different stages of the investment journey."]},
    "6":{title:"Launch of a new information service for investors",category:"General announcements",date:"16 August 2026",excerpt:"A new service designed to make investment information easier to access.",content:["A new information service has been launched to improve the investor experience.","The service provides faster access to essential investment information.","The service will be progressively developed and enriched with additional features."]},
    "7":{title:"Announcement on deadlines for submitting certain files",category:"Dates",date:"12 August 2026",excerpt:"Reminder of dates and deadlines for submitting certain files and requests.",content:["The agency reminds investors of the need to respect the deadlines set for file submission.","Investors are advised to ensure that all required documents are complete before submission.","For enquiries, the contact channels available on the website can be used."]},
    "8":{title:"Invitation to explore investment opportunities by sector",category:"Requests and offers",date:"08 August 2026",excerpt:"Explore a range of available sectors and investment opportunities.",content:["The agency invites investors to explore investment opportunities classified by sector.","The opportunities cover several economic fields that investors can assess according to their needs.","For more information, visit the investment opportunities area."]}
  }}
} as const;
