export const extraTranslations = {
  ar: {
    investorPage: {
      faq2:"كيف يمكنني التسجيل كمستثمر؟", faq2Text:"يمكنك إنشاء حساب مستثمر من خلال صفحة التسجيل وإدخال المعلومات المطلوبة، ثم متابعة مراحل مشروعك من خلال فضاء المستثمر.", faq3:"ما هي الوثائق التي أحتاجها؟", faq3Text:"تختلف الوثائق حسب طبيعة المشروع والمرحلة التي وصل إليها. يمكنك الرجوع إلى الأدلة والوثائق المتاحة للحصول على التفاصيل.", faq4:"هل يمكنني متابعة مشروعي عبر المنصة؟", faq4Text:"نعم، يتيح لك فضاء المستثمر متابعة معلومات مشروعك وطلباته ومراحله حسب الخدمات المتوفرة على المنصة.", finalOverline:"ابدأ الآن", finalTitle:"جاهز لتحويل فكرتك إلى مشروع؟", finalText:"استفد من خدمات ومعلومات الوكالة وابدأ مسارك الاستثماري في الجزائر."
    },
    sectorsPage: {
      heroOverline:"الاستثمار", heroTitle:"قطاعات الاستثمار", heroText:"اكتشف القطاعات والإمكانات الاستثمارية في الجزائر", introOverline:"قطاعات متنوعة", introTitle:"مجالات واسعة", introStrong:" للاستثمار والنمو", introText:"تتميز الجزائر بتنوع اقتصادي وإمكانات طبيعية وبشرية تسمح بتطوير مشاريع استثمارية في قطاعات متعددة.", statSectors:"قطاعات رئيسية", statWilayas:"ولاية", statActivities:"نشاطًا اقتصاديًا", statPotential:"إمكانات استثمارية", explore:"استكشف القطاع", whyOverline:"لماذا الجزائر؟", whyTitle:"بيئة توفر", whyStrong:" إمكانات حقيقية", whyText:"تتمتع الجزائر بموقع استراتيجي وموارد طبيعية وسوق محلية واسعة، إضافة إلى إمكانات بشرية ومؤهلات تسمح بتطوير مشاريع متنوعة.", strategic:"موقع استراتيجي", natural:"موارد طبيعية متنوعة", market:"سوق محلية واسعة", human:"موارد بشرية مؤهلة", ctaOverline:"جاهز للانطلاق؟", ctaTitle:"اكتشف فرص", ctaStrong:" الاستثمار", ctaText:"اختر القطاع المناسب وتعرف على الفرص والمعلومات المتاحة للمستثمر.", ctaButton:"فرص الاستثمار",
      s1:"الصناعة", s1Text:"قطاع صناعي متنوع يوفر فرصًا في الصناعات التحويلية، مواد البناء، الصناعات الغذائية وغيرها.", s1Opp:"فرص صناعية متعددة", s2:"الفلاحة", s2Text:"إمكانات واسعة للاستثمار في الإنتاج الزراعي، الصناعات الغذائية، تربية المواشي واستغلال الموارد الفلاحية.", s2Opp:"فرص فلاحية متنوعة", s3:"الطاقات المتجددة", s3Text:"إمكانات كبيرة لتطوير مشاريع الطاقة الشمسية والطاقات المتجددة والاستفادة من الموارد الطبيعية.", s3Opp:"مشاريع طاقة واعدة", s4:"السياحة", s4Text:"تنوع طبيعي وثقافي يوفر فرصًا لتطوير المشاريع الفندقية والسياحية والترفيهية.", s4Opp:"إمكانات سياحية كبيرة", s5:"التكنولوجيا والرقمنة", s5Text:"قطاع واعد لدعم الابتكار والحلول الرقمية وتطوير المؤسسات الناشئة والخدمات التكنولوجية.", s5Opp:"اقتصاد رقمي وابتكار", s6:"النقل واللوجستيك", s6Text:"فرص استثمارية مرتبطة بالنقل، التخزين، التوزيع والمنصات اللوجستية الحديثة.", s6Opp:"منصات وخدمات لوجستية", s7:"المياه والبيئة", s7Text:"مشاريع مرتبطة بإدارة الموارد المائية، معالجة المياه والحلول البيئية المستدامة.", s7Opp:"حلول بيئية مستدامة", s8:"الصحة", s8Text:"فرص لتطوير الخدمات الصحية والمنشآت الطبية والصناعات والخدمات المرتبطة بالصحة.", s8Opp:"خدمات صحية متطورة", s9:"العقار والخدمات", s9Text:"إمكانات استثمارية في العقار الاقتصادي والخدمات الموجهة للمؤسسات والمستثمرين.", s9Opp:"عقار وخدمات"
    }
  },
  fr: {
    investorPage: {
      faq2:"Comment m'inscrire comme investisseur ?", faq2Text:"Créez votre compte investisseur depuis la page d'inscription en renseignant les informations demandées, puis suivez votre projet depuis l'espace investisseur.", faq3:"Quels documents sont nécessaires ?", faq3Text:"Les documents varient selon la nature du projet et son avancement. Consultez les guides et documents disponibles pour plus de détails.", faq4:"Puis-je suivre mon projet sur la plateforme ?", faq4Text:"Oui. L'espace investisseur permet de suivre les informations, demandes et étapes de votre projet selon les services disponibles.", finalOverline:"Commencez maintenant", finalTitle:"Prêt à transformer votre idée en projet ?", finalText:"Profitez des services et informations de l'agence et démarrez votre parcours d'investissement en Algérie."
    },
    sectorsPage: {
      heroOverline:"Investissement", heroTitle:"Secteurs d'investissement", heroText:"Découvrez les secteurs et le potentiel d'investissement en Algérie", introOverline:"Secteurs diversifiés", introTitle:"Des domaines vastes", introStrong:" pour investir et croître", introText:"L'Algérie dispose d'une économie diversifiée et de ressources naturelles et humaines permettant de développer des projets dans plusieurs secteurs.", statSectors:"secteurs principaux", statWilayas:"wilayas", statActivities:"activités économiques", statPotential:"potentiel d'investissement", explore:"Explorer le secteur", whyOverline:"Pourquoi l'Algérie ?", whyTitle:"Un environnement offrant", whyStrong:" un potentiel réel", whyText:"L'Algérie bénéficie d'une position stratégique, de ressources naturelles, d'un vaste marché intérieur et de ressources humaines permettant de développer des projets variés.", strategic:"Position stratégique", natural:"Ressources naturelles diversifiées", market:"Vaste marché intérieur", human:"Ressources humaines qualifiées", ctaOverline:"Prêt à démarrer ?", ctaTitle:"Découvrez les opportunités", ctaStrong:" d'investissement", ctaText:"Choisissez le secteur adapté et découvrez les opportunités et informations disponibles.", ctaButton:"Opportunités d'investissement", s1:"Industrie", s1Text:"Un secteur industriel diversifié offrant des opportunités dans les industries de transformation, les matériaux de construction et l'agroalimentaire.", s1Opp:"Opportunités industrielles multiples", s2:"Agriculture", s2Text:"Large potentiel pour la production agricole, l'agroalimentaire, l'élevage et l'exploitation des ressources agricoles.", s2Opp:"Diverses opportunités agricoles", s3:"Énergies renouvelables", s3Text:"Fort potentiel pour développer des projets solaires et d'énergies renouvelables.", s3Opp:"Projets énergétiques prometteurs", s4:"Tourisme", s4Text:"Une diversité naturelle et culturelle offrant des opportunités dans l'hôtellerie, le tourisme et les loisirs.", s4Opp:"Fort potentiel touristique", s5:"Technologie et numérique", s5Text:"Un secteur prometteur pour l'innovation, les solutions numériques et le développement des startups.", s5Opp:"Économie numérique et innovation", s6:"Transport et logistique", s6Text:"Opportunités liées au transport, au stockage, à la distribution et aux plateformes logistiques modernes.", s6Opp:"Plateformes et services logistiques", s7:"Eau et environnement", s7Text:"Projets liés à la gestion de l'eau, au traitement des eaux et aux solutions environnementales durables.", s7Opp:"Solutions environnementales durables", s8:"Santé", s8Text:"Opportunités de développement des services de santé, établissements médicaux et industries associées.", s8Opp:"Services de santé modernes", s9:"Immobilier et services", s9Text:"Potentiel d'investissement dans l'immobilier économique et les services destinés aux entreprises et investisseurs.", s9Opp:"Immobilier et services"
    }
  },
  en: {
    investorPage: {
      faq2:"How can I register as an investor?", faq2Text:"Create an investor account from the registration page by entering the required information, then follow your project from the Investor Space.", faq3:"What documents do I need?", faq3Text:"Documents vary depending on the nature and stage of the project. Check the available guides and documents for details.", faq4:"Can I track my project on the platform?", faq4Text:"Yes. The Investor Space lets you follow your project information, requests and stages according to the available services.", finalOverline:"Start now", finalTitle:"Ready to turn your idea into a project?", finalText:"Use the agency's services and information and start your investment journey in Algeria."
    },
    sectorsPage: {
      heroOverline:"Investment", heroTitle:"Investment sectors", heroText:"Discover investment sectors and potential in Algeria", introOverline:"Diverse sectors", introTitle:"Broad fields", introStrong:" for investment and growth", introText:"Algeria has a diversified economy and natural and human resources that allow investment projects to be developed across many sectors.", statSectors:"main sectors", statWilayas:"wilayas", statActivities:"economic activities", statPotential:"investment potential", explore:"Explore sector", whyOverline:"Why Algeria?", whyTitle:"An environment offering", whyStrong:" real potential", whyText:"Algeria benefits from a strategic location, natural resources, a broad domestic market and human capabilities that support diverse projects.", strategic:"Strategic location", natural:"Diverse natural resources", market:"Broad domestic market", human:"Qualified human resources", ctaOverline:"Ready to start?", ctaTitle:"Discover investment", ctaStrong:" opportunities", ctaText:"Choose the right sector and learn about opportunities and information available to investors.", ctaButton:"Investment opportunities", s1:"Industry", s1Text:"A diversified industrial sector offering opportunities in manufacturing, construction materials and food industries.", s1Opp:"Multiple industrial opportunities", s2:"Agriculture", s2Text:"Strong potential in agricultural production, food processing, livestock and agricultural resources.", s2Opp:"Diverse agricultural opportunities", s3:"Renewable energy", s3Text:"Strong potential for solar and renewable energy projects.", s3Opp:"Promising energy projects", s4:"Tourism", s4Text:"Natural and cultural diversity offering opportunities in hotels, tourism and leisure.", s4Opp:"Strong tourism potential", s5:"Technology and digital", s5Text:"A promising sector supporting innovation, digital solutions and startup development.", s5Opp:"Digital economy and innovation", s6:"Transport and logistics", s6Text:"Investment opportunities related to transport, storage, distribution and modern logistics platforms.", s6Opp:"Logistics platforms and services", s7:"Water and environment", s7Text:"Projects related to water management, treatment and sustainable environmental solutions.", s7Opp:"Sustainable environmental solutions", s8:"Healthcare", s8Text:"Opportunities to develop healthcare services, medical facilities and related industries.", s8Opp:"Modern healthcare services", s9:"Real estate and services", s9Text:"Investment potential in economic real estate and services for companies and investors.", s9Opp:"Real estate and services"
    }
  }
} as const;
