export const investorFormsTranslations = {
  ar: {
    projectForm: {
      newProject: "مشروع جديد", addProject: "إضافة مشروع استثماري", title: "عنوان المشروع", titlePlaceholder: "مثال: إنشاء مركز تكنولوجي", description: "وصف المشروع", descriptionPlaceholder: "قدم وصفاً واضحاً ومفصلاً عن المشروع وأهدافه وطبيعته.", sector: "القطاع الاستثماري", selectSector: "اختر القطاع", wilaya: "الولاية", wilayaPlaceholder: "مثال: الجزائر", commune: "البلدية", communePlaceholder: "مثال: الجزائر الوسطى", address: "العنوان", addressPlaceholder: "العنوان الكامل للمشروع", investmentAmount: "مبلغ الاستثمار", investmentPlaceholder: "مثال: 25000000", amountHint: "المبلغ بالدينار الجزائري DA", jobs: "عدد مناصب العمل", jobsPlaceholder: "مثال: 50", area: "المساحة", areaPlaceholder: "مثال: 2500", areaUnit: "وحدة المساحة", squareMeter: "متر مربع (m²)", hectare: "هكتار (ha)", startDate: "تاريخ بداية المشروع", endDate: "تاريخ نهاية المشروع", sending: "جاري إرسال المشروع...", send: "إرسال المشروع إلى الإدارة", reset: "إعادة تعيين"
    },
    requestForm: {
      services: "الخدمات", addRequest: "إضافة طلب استثماري", type: "نوع الطلب", authorization: "طلب ترخيص", approval: "طلب اعتماد", advantage: "طلب امتياز", land: "طلب عقار استثماري", support: "طلب مرافقة", information: "طلب معلومات", other: "طلب آخر", project: "المشروع المرتبط", noProject: "بدون مشروع مرتبط", subject: "موضوع الطلب", subjectPlaceholder: "مثال: طلب اعتماد مشروع استثماري", amount: "المبلغ المطلوب (دج)", amountPlaceholder: "0", wilaya: "الولاية", wilayaPlaceholder: "مثال: باتنة", priority: "الأولوية", low: "منخفضة", normal: "عادية", high: "مرتفعة", urgent: "عاجلة", details: "تفاصيل الطلب", detailsPlaceholder: "اشرح طلبك بالتفصيل...", documents: "الوثائق المرفقة", filesHelp: "يمكن إرفاق عدة وثائق، بحد أقصى 10 ميغابايت لكل وثيقة.", sending: "جاري الإرسال...", send: "إرسال الطلب", clear: "مسح"
    }
  },
  fr: {
    projectForm: {
      newProject: "Nouveau projet", addProject: "Ajouter un projet d'investissement", title: "Titre du projet", titlePlaceholder: "Exemple : Création d'un centre technologique", description: "Description du projet", descriptionPlaceholder: "Présentez clairement le projet, ses objectifs et sa nature.", sector: "Secteur d'investissement", selectSector: "Sélectionner le secteur", wilaya: "Wilaya", wilayaPlaceholder: "Exemple : Alger", commune: "Commune", communePlaceholder: "Exemple : Alger-Centre", address: "Adresse", addressPlaceholder: "Adresse complète du projet", investmentAmount: "Montant de l'investissement", investmentPlaceholder: "Exemple : 25000000", amountHint: "Montant en dinars algériens DA", jobs: "Nombre d'emplois", jobsPlaceholder: "Exemple : 50", area: "Superficie", areaPlaceholder: "Exemple : 2500", areaUnit: "Unité de superficie", squareMeter: "Mètre carré (m²)", hectare: "Hectare (ha)", startDate: "Date de début du projet", endDate: "Date de fin du projet", sending: "Envoi du projet...", send: "Envoyer le projet à l'administration", reset: "Réinitialiser"
    },
    requestForm: {
      services: "Services", addRequest: "Ajouter une demande d'investissement", type: "Type de demande", authorization: "Demande d'autorisation", approval: "Demande d'agrément", advantage: "Demande d'avantage", land: "Demande de foncier d'investissement", support: "Demande d'accompagnement", information: "Demande d'information", other: "Autre demande", project: "Projet associé", noProject: "Aucun projet associé", subject: "Objet de la demande", subjectPlaceholder: "Exemple : Demande d'agrément d'un projet d'investissement", amount: "Montant demandé (DA)", amountPlaceholder: "0", wilaya: "Wilaya", wilayaPlaceholder: "Exemple : Batna", priority: "Priorité", low: "Basse", normal: "Normale", high: "Haute", urgent: "Urgente", details: "Détails de la demande", detailsPlaceholder: "Expliquez votre demande en détail...", documents: "Documents joints", filesHelp: "Plusieurs documents peuvent être joints, avec un maximum de 10 Mo par document.", sending: "Envoi...", send: "Envoyer la demande", clear: "Effacer"
    }
  },
  en: {
    projectForm: {
      newProject: "New project", addProject: "Add investment project", title: "Project title", titlePlaceholder: "Example: Technology center creation", description: "Project description", descriptionPlaceholder: "Provide a clear and detailed description of the project, its objectives and nature.", sector: "Investment sector", selectSector: "Select sector", wilaya: "Wilaya", wilayaPlaceholder: "Example: Algiers", commune: "Commune", communePlaceholder: "Example: Algiers Centre", address: "Address", addressPlaceholder: "Full project address", investmentAmount: "Investment amount", investmentPlaceholder: "Example: 25000000", amountHint: "Amount in Algerian dinars DA", jobs: "Number of jobs", jobsPlaceholder: "Example: 50", area: "Area", areaPlaceholder: "Example: 2500", areaUnit: "Area unit", squareMeter: "Square meter (m²)", hectare: "Hectare (ha)", startDate: "Project start date", endDate: "Project end date", sending: "Sending project...", send: "Send project to administration", reset: "Reset"
    },
    requestForm: {
      services: "Services", addRequest: "Add investment request", type: "Request type", authorization: "Authorization request", approval: "Approval request", advantage: "Benefit request", land: "Investment land request", support: "Support request", information: "Information request", other: "Other request", project: "Related project", noProject: "No related project", subject: "Request subject", subjectPlaceholder: "Example: Investment project approval request", amount: "Requested amount (DA)", amountPlaceholder: "0", wilaya: "Wilaya", wilayaPlaceholder: "Example: Batna", priority: "Priority", low: "Low", normal: "Normal", high: "High", urgent: "Urgent", details: "Request details", detailsPlaceholder: "Explain your request in detail...", documents: "Attached documents", filesHelp: "Multiple documents can be attached, up to 10 MB per document.", sending: "Sending...", send: "Send request", clear: "Clear"
    }
  }
};
