export const newsDetailsTranslations = {
  ar:{
    page:{notFound:"الخبر غير موجود",notFoundText:"عذرًا، لم نتمكن من العثور على الخبر الذي تبحث عنه.",back:"العودة إلى الأخبار",details:"تفاصيل الخبر",agencyNews:"أخبار الوكالة",share:"مشاركة الخبر",facebook:"مشاركة عبر فيسبوك",x:"مشاركة عبر X",linkedin:"مشاركة عبر لينكدإن",media:"المركز الإعلامي",mediaText:"تابع آخر أخبار الوكالة والمستجدات المتعلقة بالاستثمار.",allNews:"جميع الأخبار",investment:"فرص استثمارية",investmentTitle:"اكتشف فرص الاستثمار",investmentText:"استكشف القطاعات والمشاريع والفرص الاستثمارية المتاحة.",discover:"اكتشف الفرص",help:"هل تحتاج إلى مساعدة؟",helpText:"يمكنك التواصل معنا للحصول على المزيد من المعلومات.",contact:"اتصل بنا",backAll:"العودة إلى جميع الأخبار"},
    articles:{
      "1":{title:"الوكالة الجزائرية لترقية الاستثمار تعزز خدماتها للمستثمرين",category:"أخبار الوكالة",date:"02 سبتمبر 2026",icon:"bi-building",content:["تواصل الوكالة الجزائرية لترقية الاستثمار تطوير خدماتها الموجهة للمستثمرين بهدف تحسين تجربة المستثمر وتسهيل الوصول إلى المعلومات والخدمات المتعلقة بالمشاريع الاستثمارية.","وتندرج هذه الجهود ضمن مسار يهدف إلى توفير بيئة استثمارية أكثر وضوحًا وفعالية، مع تعزيز المرافقة وتوفير المعلومات التي يحتاجها أصحاب المشاريع في مختلف المراحل.","كما تساهم الخدمات الرقمية في تقريب المعلومات من المستثمر وتسهيل الوصول إلى الموارد والأدلة المتعلقة بالاستثمار في الجزائر."]},
      "2":{title:"فرص استثمارية جديدة في عدد من القطاعات",category:"الاستثمار",date:"28 أوت 2026",icon:"bi-graph-up-arrow",content:["تتوفر في الجزائر إمكانات استثمارية متنوعة في عدد من القطاعات الاقتصادية، وهو ما يفتح المجال أمام المستثمرين لاستكشاف مشاريع وفرص جديدة.","وتشمل هذه الإمكانات قطاعات الصناعة والفلاحة والطاقة والسياحة والتكنولوجيا والنقل واللوجستيك وغيرها من المجالات.","ويمكن للمستثمر الاطلاع على الفرص المتاحة ودراسة مدى ملاءمتها مع أهداف مشروعه وخبرته وإمكاناته."]},
      "3":{title:"لقاء حول تطوير بيئة الأعمال والاستثمار",category:"فعاليات",date:"25 أوت 2026",icon:"bi-people",content:["تم تنظيم لقاء حول تطوير بيئة الأعمال والاستثمار ومناقشة عدد من المحاور المرتبطة بتحسين مرافقة المستثمرين.","وشكل اللقاء فرصة لتبادل الآراء ومناقشة التحديات التي تواجه أصحاب المشاريع والبحث عن حلول عملية تساعد على تحسين المسار الاستثماري.","كما تم التأكيد على أهمية تطوير الخدمات وتعزيز التواصل مع المستثمرين."]},
      "4":{title:"مستجدات حول الخدمات الرقمية للمستثمر",category:"مستجدات",date:"20 أوت 2026",icon:"bi-laptop",content:["تشهد الخدمات الرقمية الموجهة للمستثمر تطورًا مستمرًا بهدف تسهيل الوصول إلى المعلومات والموارد المتعلقة بالمشاريع الاستثمارية.","وتسمح الحلول الرقمية بتوفير المعلومات بشكل أسرع وأكثر تنظيمًا، مما يساعد المستثمر على متابعة مختلف مراحل مشروعه.","وتشكل الرقمنة عنصرًا مهمًا في تحسين جودة الخدمات وتطوير العلاقة بين المستثمر والهيئات المعنية."]},
      "5":{title:"تطوير فرص الاستثمار في القطاع الصناعي",category:"الاستثمار",date:"16 أوت 2026",icon:"bi-buildings",content:["يمثل القطاع الصناعي أحد المجالات المهمة أمام المستثمرين الراغبين في تطوير مشاريع منتجة وخلق قيمة مضافة.","وتوفر مختلف مناطق الجزائر إمكانات متنوعة يمكن استغلالها لإنجاز مشاريع صناعية في عدة تخصصات.","ويساهم تطوير الاستثمار الصناعي في دعم النشاط الاقتصادي وخلق فرص العمل وتعزيز الإنتاج المحلي."]},
      "6":{title:"ندوة تعريفية حول مسار المستثمر",category:"فعاليات",date:"12 أوت 2026",icon:"bi-mic",content:["شكلت الندوة التعريفية فرصة لتقديم معلومات حول مختلف مراحل إنجاز المشروع الاستثماري.","وتضمنت الندوة توضيحات حول إعداد فكرة المشروع ودراسة المشروع والإجراءات وصولًا إلى مرحلة الإنجاز.","كما تم التطرق إلى أهمية الحصول على المعلومات الصحيحة قبل اتخاذ القرارات المتعلقة بالمشروع."]},
      "7":{title:"إطلاق موارد جديدة لفائدة المستثمرين",category:"مستجدات",date:"08 أوت 2026",icon:"bi-file-earmark-text",content:["تم توفير مجموعة من الموارد والأدلة التي تساعد المستثمرين وأصحاب المشاريع على التعرف على مختلف مراحل المسار الاستثماري.","وتوفر هذه الموارد معلومات عملية يمكن الاستفادة منها أثناء إعداد المشروع ودراسة احتياجاته.","وتهدف هذه المبادرات إلى تسهيل الوصول إلى المعلومة وتحسين تجربة المستثمر."]},
      "8":{title:"تشجيع الاستثمار في الطاقات المتجددة",category:"الاستثمار",date:"03 أوت 2026",icon:"bi-sun",content:["يمثل قطاع الطاقات المتجددة مجالًا واعدًا للاستثمار بالنظر إلى الإمكانات المتاحة وفرص تطوير مشاريع جديدة.","ويمكن للمشاريع المتعلقة بالطاقة الشمسية والطاقات النظيفة أن تساهم في دعم التنمية الاقتصادية وتنويع مصادر الطاقة.","ويظل هذا المجال من القطاعات التي يمكن للمستثمرين استكشاف إمكاناتها وفرصها المستقبلية."]},
      "9":{title:"اجتماع حول تحسين مرافقة المستثمر",category:"أخبار الوكالة",date:"29 جويلية 2026",icon:"bi-chat-square-text",content:["تم خلال الاجتماع مناقشة مجموعة من المحاور المتعلقة بتحسين مرافقة المستثمرين وتطوير الخدمات المقدمة لهم.","وشملت النقاشات أهمية تبسيط المعلومات وتحسين التواصل وتوفير توجيه أكثر فعالية لأصحاب المشاريع.","وتأتي هذه الجهود ضمن العمل المستمر على تطوير بيئة مناسبة لإنجاز المشاريع الاستثمارية."]}
    }
  },
  fr:{
    page:{notFound:"Actualité introuvable",notFoundText:"Désolé, nous n'avons pas trouvé l'actualité recherchée.",back:"Retour aux actualités",details:"Détails de l'actualité",agencyNews:"Actualités de l'agence",share:"Partager l'actualité",facebook:"Partager sur Facebook",x:"Partager via X",linkedin:"Partager sur LinkedIn",media:"Centre média",mediaText:"Suivez les dernières actualités de l'agence et les nouveautés liées à l'investissement.",allNews:"Toutes les actualités",investment:"Opportunités d'investissement",investmentTitle:"Découvrez les opportunités d'investissement",investmentText:"Explorez les secteurs, projets et opportunités d'investissement disponibles.",discover:"Découvrir les opportunités",help:"Besoin d'aide ?",helpText:"Contactez-nous pour obtenir plus d'informations.",contact:"Nous contacter",backAll:"Retour à toutes les actualités"},
    articles:{
      "1":{title:"L'Agence algérienne de promotion de l'investissement renforce ses services aux investisseurs",category:"Actualités de l'agence",date:"02 septembre 2026",icon:"bi-building",content:["L'Agence algérienne de promotion de l'investissement poursuit le développement de ses services destinés aux investisseurs afin d'améliorer leur expérience et de faciliter l'accès aux informations et services liés aux projets d'investissement.","Ces efforts s'inscrivent dans une démarche visant à offrir un environnement d'investissement plus clair et efficace, tout en renforçant l'accompagnement et l'information des porteurs de projets.","Les services numériques contribuent également à rapprocher l'information des investisseurs et à faciliter l'accès aux ressources et guides liés à l'investissement en Algérie."]},
      "2":{title:"De nouvelles opportunités d'investissement dans plusieurs secteurs",category:"Investissement",date:"28 août 2026",icon:"bi-graph-up-arrow",content:["L'Algérie dispose d'un potentiel d'investissement diversifié dans plusieurs secteurs économiques, ouvrant la voie à de nouveaux projets et opportunités.","Ce potentiel couvre notamment l'industrie, l'agriculture, l'énergie, le tourisme, la technologie, le transport et la logistique.","Les investisseurs peuvent consulter les opportunités disponibles et évaluer leur adéquation avec leurs objectifs, leur expérience et leurs capacités."]},
      "3":{title:"Rencontre sur le développement de l'environnement des affaires et de l'investissement",category:"Événements",date:"25 août 2026",icon:"bi-people",content:["Une rencontre consacrée au développement de l'environnement des affaires et de l'investissement a été organisée afin d'aborder plusieurs axes liés à l'accompagnement des investisseurs.","La rencontre a permis d'échanger sur les défis rencontrés par les porteurs de projets et de rechercher des solutions pratiques pour améliorer le parcours d'investissement.","L'importance du développement des services et du renforcement de la communication avec les investisseurs a également été soulignée."]},
      "4":{title:"Actualités des services numériques pour l'investisseur",category:"Nouveautés",date:"20 août 2026",icon:"bi-laptop",content:["Les services numériques destinés aux investisseurs évoluent continuellement afin de faciliter l'accès aux informations et ressources liées aux projets d'investissement.","Les solutions numériques permettent de fournir des informations plus rapidement et de manière plus structurée, aidant ainsi l'investisseur à suivre les différentes étapes de son projet.","La digitalisation constitue un élément important pour améliorer la qualité des services et la relation entre l'investisseur et les organismes concernés."]},
      "5":{title:"Développement des opportunités d'investissement dans le secteur industriel",category:"Investissement",date:"16 août 2026",icon:"bi-buildings",content:["Le secteur industriel constitue un domaine important pour les investisseurs souhaitant développer des projets productifs et créer de la valeur ajoutée.","Les différentes régions d'Algérie offrent des potentiels variés pouvant être exploités pour réaliser des projets industriels dans plusieurs spécialités.","Le développement de l'investissement industriel contribue à soutenir l'activité économique, créer des emplois et renforcer la production locale."]},
      "6":{title:"Séminaire d'information sur le parcours de l'investisseur",category:"Événements",date:"12 août 2026",icon:"bi-mic",content:["Le séminaire d'information a permis de présenter les différentes étapes de réalisation d'un projet d'investissement.","Il a notamment abordé la préparation de l'idée de projet, son étude et les procédures jusqu'à la phase de réalisation.","L'importance de disposer d'informations fiables avant de prendre les décisions liées au projet a également été soulignée."]},
      "7":{title:"Lancement de nouvelles ressources pour les investisseurs",category:"Nouveautés",date:"08 août 2026",icon:"bi-file-earmark-text",content:["Un ensemble de ressources et de guides a été mis à disposition pour aider les investisseurs et porteurs de projets à comprendre les différentes étapes du parcours d'investissement.","Ces ressources fournissent des informations pratiques utiles lors de la préparation du projet et de l'étude de ses besoins.","Ces initiatives visent à faciliter l'accès à l'information et à améliorer l'expérience de l'investisseur."]},
      "8":{title:"Encourager l'investissement dans les énergies renouvelables",category:"Investissement",date:"03 août 2026",icon:"bi-sun",content:["Le secteur des énergies renouvelables constitue un domaine d'investissement prometteur compte tenu du potentiel disponible et des possibilités de développer de nouveaux projets.","Les projets liés à l'énergie solaire et aux énergies propres peuvent contribuer au développement économique et à la diversification des sources d'énergie.","Ce domaine demeure l'un des secteurs dont les investisseurs peuvent explorer le potentiel et les perspectives futures."]},
      "9":{title:"Réunion sur l'amélioration de l'accompagnement des investisseurs",category:"Actualités de l'agence",date:"29 juillet 2026",icon:"bi-chat-square-text",content:["La réunion a porté sur plusieurs axes liés à l'amélioration de l'accompagnement des investisseurs et au développement des services qui leur sont proposés.","Les discussions ont notamment abordé la simplification de l'information, l'amélioration de la communication et un accompagnement plus efficace des porteurs de projets.","Ces efforts s'inscrivent dans le travail continu visant à développer un environnement favorable à la réalisation des projets d'investissement."]}
    }
  },
  en:{
    page:{notFound:"News not found",notFoundText:"Sorry, we could not find the news article you are looking for.",back:"Back to news",details:"News details",agencyNews:"Agency news",share:"Share this news",facebook:"Share on Facebook",x:"Share via X",linkedin:"Share on LinkedIn",media:"Media center",mediaText:"Follow the latest agency news and investment updates.",allNews:"All news",investment:"Investment opportunities",investmentTitle:"Discover investment opportunities",investmentText:"Explore available sectors, projects and investment opportunities.",discover:"Discover opportunities",help:"Need help?",helpText:"Contact us for more information.",contact:"Contact us",backAll:"Back to all news"},
    articles:{
      "1":{title:"The Algerian Agency for Investment Promotion strengthens its investor services",category:"Agency news",date:"02 September 2026",icon:"bi-building",content:["The Algerian Agency for Investment Promotion continues to develop services for investors to improve the investor experience and facilitate access to information and services related to investment projects.","These efforts are part of a drive to provide a clearer and more effective investment environment while strengthening support and information for project owners.","Digital services also help bring information closer to investors and facilitate access to investment resources and guides in Algeria."]},
      "2":{title:"New investment opportunities across several sectors",category:"Investment",date:"28 August 2026",icon:"bi-graph-up-arrow",content:["Algeria has diverse investment potential across several economic sectors, opening the way for investors to explore new projects and opportunities.","This potential includes industry, agriculture, energy, tourism, technology, transport and logistics and other fields.","Investors can review available opportunities and assess their suitability for their objectives, experience and capabilities."]},
      "3":{title:"Meeting on developing the business and investment environment",category:"Events",date:"25 August 2026",icon:"bi-people",content:["A meeting was held on developing the business and investment environment and discussing areas related to improving investor support.","The meeting provided an opportunity to exchange views, discuss challenges facing project owners and seek practical solutions to improve the investment journey.","The importance of developing services and strengthening communication with investors was also emphasized."]},
      "4":{title:"Updates on digital services for investors",category:"Updates",date:"20 August 2026",icon:"bi-laptop",content:["Digital services for investors continue to evolve to facilitate access to information and resources related to investment projects.","Digital solutions provide information faster and in a more organized way, helping investors follow the different stages of their projects.","Digitalization is an important element in improving service quality and the relationship between investors and relevant institutions."]},
      "5":{title:"Developing investment opportunities in the industrial sector",category:"Investment",date:"16 August 2026",icon:"bi-buildings",content:["The industrial sector is an important field for investors seeking to develop productive projects and create added value.","Different regions of Algeria offer varied potential that can be used to develop industrial projects in several specialties.","Industrial investment supports economic activity, job creation and stronger local production."]},
      "6":{title:"Information seminar on the investor journey",category:"Events",date:"12 August 2026",icon:"bi-mic",content:["The information seminar provided an overview of the different stages involved in implementing an investment project.","It covered project idea preparation, project assessment and procedures through to implementation.","The importance of obtaining reliable information before making project-related decisions was also discussed."]},
      "7":{title:"Launch of new resources for investors",category:"Updates",date:"08 August 2026",icon:"bi-file-earmark-text",content:["A set of resources and guides has been made available to help investors and project owners understand the different stages of the investment journey.","These resources provide practical information that can be used while preparing the project and assessing its needs.","These initiatives aim to facilitate access to information and improve the investor experience."]},
      "8":{title:"Promoting investment in renewable energy",category:"Investment",date:"03 August 2026",icon:"bi-sun",content:["Renewable energy is a promising investment field given the available potential and opportunities to develop new projects.","Projects related to solar and clean energy can contribute to economic development and diversify energy sources.","This remains a sector whose potential and future opportunities investors can explore."]},
      "9":{title:"Meeting on improving investor support",category:"Agency news",date:"29 July 2026",icon:"bi-chat-square-text",content:["The meeting addressed several areas related to improving investor support and developing services provided to them.","Discussions covered the importance of simplifying information, improving communication and providing more effective guidance to project owners.","These efforts are part of the ongoing work to develop a suitable environment for implementing investment projects."]}
    }
  }
} as const;
