-- ============================================================
-- AAPI - BASE DE DONNÉES
-- Agence Algérienne de Promotion de l'Investissement
-- ============================================================


-- ============================================================
-- 0. WILAYAS D'ALGERIE (58 wilayas historiques)
-- ============================================================

DROP TABLE IF EXISTS wilayas;

CREATE TABLE wilayas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code CHAR(2) NOT NULL UNIQUE,
    nom_fr VARCHAR(100) NOT NULL,
    nom_ar VARCHAR(100) NOT NULL,
    statut TEXT NOT NULL DEFAULT 'actif',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
);

INSERT INTO wilayas (code, nom_fr, nom_ar) VALUES
('01','Adrar','أدرار'),
('02','Chlef','الشلف'),
('03','Laghouat','الأغواط'),
('04','Oum El Bouaghi','أم البواقي'),
('05','Batna','باتنة'),
('06','Béjaïa','بجاية'),
('07','Biskra','بسكرة'),
('08','Béchar','بشار'),
('09','Blida','البليدة'),
('10','Bouira','البويرة'),
('11','Tamanrasset','تمنراست'),
('12','Tébessa','تبسة'),
('13','Tlemcen','تلمسان'),
('14','Tiaret','تيارت'),
('15','Tizi Ouzou','تيزي وزو'),
('16','Alger','الجزائر'),
('17','Djelfa','الجلفة'),
('18','Jijel','جيجل'),
('19','Sétif','سطيف'),
('20','Saïda','سعيدة'),
('21','Skikda','سكيكدة'),
('22','Sidi Bel Abbès','سيدي بلعباس'),
('23','Annaba','عنابة'),
('24','Guelma','قالمة'),
('25','Constantine','قسنطينة'),
('26','Médéa','المدية'),
('27','Mostaganem','مستغانم'),
('28','M’Sila','المسيلة'),
('29','Mascara','معسكر'),
('30','Ouargla','ورقلة'),
('31','Oran','وهران'),
('32','El Bayadh','البيض'),
('33','Illizi','إليزي'),
('34','Bordj Bou Arréridj','برج بوعريريج'),
('35','Boumerdès','بومرداس'),
('36','El Tarf','الطارف'),
('37','Tindouf','تندوف'),
('38','Tissemsilt','تيسمسيلت'),
('39','El Oued','الوادي'),
('40','Khenchela','خنشلة'),
('41','Souk Ahras','سوق أهراس'),
('42','Tipaza','تيبازة'),
('43','Mila','ميلة'),
('44','Aïn Defla','عين الدفلى'),
('45','Naâma','النعامة'),
('46','Aïn Témouchent','عين تموشنت'),
('47','Ghardaïa','غرداية'),
('48','Relizane','غليزان'),
('49','Timimoun','تيميمون'),
('50','Bordj Badji Mokhtar','برج باجي مختار'),
('51','Ouled Djellal','أولاد جلال'),
('52','Béni Abbès','بني عباس'),
('53','In Salah','عين صالح'),
('54','In Guezzam','عين قزام'),
('55','Touggourt','تقرت'),
('56','Djanet','جانت'),
('57','El M’Ghair','المغير'),
('58','El Meniaa','المنيعة');


-- ============================================================
-- 1. UTILISATEURS
-- ============================================================

DROP TABLE IF EXISTS notifications;
DROP TABLE IF EXISTS messages;
DROP TABLE IF EXISTS documents;
DROP TABLE IF EXISTS investment_requests;
DROP TABLE IF EXISTS investments;
DROP TABLE IF EXISTS project_sectors;
DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS sectors;
DROP TABLE IF EXISTS investor_profiles;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS announcements;
DROP TABLE IF EXISTS news;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    nom VARCHAR(100) NOT NULL,
    prenom VARCHAR(100) NOT NULL,

    email VARCHAR(180) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,

    telephone VARCHAR(30) DEFAULT NULL,

    role TEXT NOT NULL DEFAULT 'investisseur',

    statut TEXT NOT NULL DEFAULT 'actif',

    photo VARCHAR(255) DEFAULT NULL,

    last_login TIMESTAMP DEFAULT NULL,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
);


-- ============================================================
-- 2. PROFILS INVESTISSEURS
-- ============================================================

CREATE TABLE investor_profiles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id INTEGER NOT NULL,

    type_investisseur TEXT NOT NULL DEFAULT 'personne_physique',

    nom_entreprise VARCHAR(180) DEFAULT NULL,

    registre_commerce VARCHAR(100) DEFAULT NULL,
    nif VARCHAR(100) DEFAULT NULL,
    nis VARCHAR(100) DEFAULT NULL,

    wilaya VARCHAR(100) DEFAULT NULL,
    commune VARCHAR(100) DEFAULT NULL,
    adresse TEXT DEFAULT NULL,

    site_web VARCHAR(255) DEFAULT NULL,

    secteur_activite VARCHAR(150) DEFAULT NULL,

    description TEXT DEFAULT NULL,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT unique_investor_user UNIQUE (user_id),

    CONSTRAINT fk_investor_profile_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);


-- ============================================================
-- 3. SECTEURS
-- ============================================================

CREATE TABLE sectors (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    nom VARCHAR(150) NOT NULL,
    slug VARCHAR(180) NOT NULL UNIQUE,

    description TEXT DEFAULT NULL,

    icone VARCHAR(100) DEFAULT NULL,

    statut TEXT NOT NULL DEFAULT 'actif',

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
);


-- ============================================================
-- 4. PROJETS D'INVESTISSEMENT
-- ============================================================

CREATE TABLE projects (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id INTEGER DEFAULT NULL,

    titre VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL UNIQUE,

    description TEXT DEFAULT NULL,

    wilaya VARCHAR(100) DEFAULT NULL,
    commune VARCHAR(100) DEFAULT NULL,

    adresse TEXT DEFAULT NULL,

    montant_investissement DECIMAL(18,2) DEFAULT 0.00,

    nombre_emplois INTEGER DEFAULT 0,

    superficie DECIMAL(12,2) DEFAULT NULL,

    unite_superficie VARCHAR(30) DEFAULT 'm²',

    statut TEXT NOT NULL DEFAULT 'brouillon',

    image VARCHAR(255) DEFAULT NULL,

    date_debut DATE DEFAULT NULL,
    date_fin DATE DEFAULT NULL,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,



    CONSTRAINT fk_project_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE SET NULL
        ON UPDATE CASCADE
);


-- ============================================================
-- 5. RELATION PROJETS / SECTEURS
-- ============================================================

CREATE TABLE project_sectors (
    project_id INTEGER NOT NULL,
    sector_id INTEGER NOT NULL,

    PRIMARY KEY (project_id, sector_id),

    CONSTRAINT fk_project_sector_project
        FOREIGN KEY (project_id)
        REFERENCES projects(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT fk_project_sector_sector
        FOREIGN KEY (sector_id)
        REFERENCES sectors(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);


-- ============================================================
-- 6. INVESTISSEMENTS
-- ============================================================

CREATE TABLE investments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id INTEGER NOT NULL,
    project_id INTEGER NOT NULL,

    montant DECIMAL(18,2) NOT NULL DEFAULT 0.00,

    date_investissement DATE DEFAULT NULL,

    statut TEXT NOT NULL DEFAULT 'en_attente',

    reference VARCHAR(100) NOT NULL UNIQUE,

    notes TEXT DEFAULT NULL,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,



    CONSTRAINT fk_investment_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT fk_investment_project
        FOREIGN KEY (project_id)
        REFERENCES projects(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);


-- ============================================================
-- 7. DEMANDES D'INVESTISSEMENT
-- ============================================================

CREATE TABLE investment_requests (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id INTEGER NOT NULL,

    projet_id INTEGER DEFAULT NULL,

    type_demande TEXT NOT NULL DEFAULT 'information',

    objet VARCHAR(255) NOT NULL,

    description TEXT NOT NULL,

    montant_demande DECIMAL(18,2) DEFAULT NULL,

    wilaya VARCHAR(100) DEFAULT NULL,

    statut TEXT NOT NULL DEFAULT 'nouvelle',

    priorite TEXT NOT NULL DEFAULT 'normale',

    reponse TEXT DEFAULT NULL,

    traite_par INTEGER DEFAULT NULL,

    date_traitement TIMESTAMP DEFAULT NULL,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,




    CONSTRAINT fk_request_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT fk_request_project
        FOREIGN KEY (projet_id)
        REFERENCES projects(id)
        ON DELETE SET NULL
        ON UPDATE CASCADE,

    CONSTRAINT fk_request_agent
        FOREIGN KEY (traite_par)
        REFERENCES users(id)
        ON DELETE SET NULL
        ON UPDATE CASCADE
);


-- ============================================================
-- 8. DOCUMENTS
-- ============================================================

CREATE TABLE documents (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id INTEGER NOT NULL,

    project_id INTEGER DEFAULT NULL,
    request_id INTEGER DEFAULT NULL,

    titre VARCHAR(255) NOT NULL,

    type_document TEXT NOT NULL DEFAULT 'autre',

    fichier VARCHAR(500) NOT NULL,

    nom_original VARCHAR(255) DEFAULT NULL,

    extension VARCHAR(20) DEFAULT NULL,

    taille BIGINTEGER DEFAULT NULL,

    statut TEXT NOT NULL DEFAULT 'en_attente',

    commentaire TEXT DEFAULT NULL,

    uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,



    CONSTRAINT fk_document_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT fk_document_project
        FOREIGN KEY (project_id)
        REFERENCES projects(id)
        ON DELETE SET NULL
        ON UPDATE CASCADE,

    CONSTRAINT fk_document_request
        FOREIGN KEY (request_id)
        REFERENCES investment_requests(id)
        ON DELETE SET NULL
        ON UPDATE CASCADE
);


-- ============================================================
-- 9. MESSAGES
-- ============================================================

CREATE TABLE messages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    sender_id INTEGER DEFAULT NULL,
    receiver_id INTEGER DEFAULT NULL,

    sujet VARCHAR(255) NOT NULL,

    contenu TEXT NOT NULL,

    lu SMALLINT NOT NULL DEFAULT 0,

    date_lecture TIMESTAMP DEFAULT NULL,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,



    CONSTRAINT fk_message_sender
        FOREIGN KEY (sender_id)
        REFERENCES users(id)
        ON DELETE SET NULL
        ON UPDATE CASCADE,

    CONSTRAINT fk_message_receiver
        FOREIGN KEY (receiver_id)
        REFERENCES users(id)
        ON DELETE SET NULL
        ON UPDATE CASCADE
);


-- ============================================================
-- 10. NOTIFICATIONS
-- ============================================================

CREATE TABLE notifications (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id INTEGER NOT NULL,

    titre VARCHAR(255) NOT NULL,

    message TEXT NOT NULL,

    type TEXT NOT NULL DEFAULT 'info',

    lien VARCHAR(500) DEFAULT NULL,

    lu SMALLINT NOT NULL DEFAULT 0,

    date_lecture TIMESTAMP DEFAULT NULL,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,


    CONSTRAINT fk_notification_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);


-- ============================================================
-- 11. ACTUALITÉS
-- ============================================================

CREATE TABLE news (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    titre VARCHAR(255) NOT NULL,

    slug VARCHAR(255) NOT NULL UNIQUE,

    resume TEXT DEFAULT NULL,

    contenu TEXT NOT NULL,

    image VARCHAR(500) DEFAULT NULL,

    auteur_id INTEGER DEFAULT NULL,

    statut TEXT NOT NULL DEFAULT 'brouillon',

    date_publication TIMESTAMP DEFAULT NULL,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,


    CONSTRAINT fk_news_author
        FOREIGN KEY (auteur_id)
        REFERENCES users(id)
        ON DELETE SET NULL
        ON UPDATE CASCADE
);


-- ============================================================
-- 12. ANNONCES
-- ============================================================

CREATE TABLE announcements (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    titre VARCHAR(255) NOT NULL,

    slug VARCHAR(255) NOT NULL UNIQUE,

    contenu TEXT NOT NULL,

    image VARCHAR(500) DEFAULT NULL,

    auteur_id INTEGER DEFAULT NULL,

    statut TEXT NOT NULL DEFAULT 'brouillon',

    date_publication TIMESTAMP DEFAULT NULL,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,


    CONSTRAINT fk_announcement_author
        FOREIGN KEY (auteur_id)
        REFERENCES users(id)
        ON DELETE SET NULL
        ON UPDATE CASCADE
);


-- ============================================================
-- 13. ÉVÉNEMENTS
-- ============================================================

CREATE TABLE events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    titre VARCHAR(255) NOT NULL,

    description TEXT DEFAULT NULL,

    lieu VARCHAR(255) DEFAULT NULL,

    adresse VARCHAR(500) DEFAULT NULL,

    image VARCHAR(500) DEFAULT NULL,

    date_debut TIMESTAMP NOT NULL,
    date_fin TIMESTAMP DEFAULT NULL,

    statut TEXT NOT NULL DEFAULT 'a_venir',

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
);


-- ============================================================
-- 14. SECTEURS DE BASE
-- ============================================================

INSERT INTO sectors
    (nom, slug, description, icone)
VALUES
(
    'Agriculture',
    'agriculture',
    'Investissements dans le secteur agricole et agroalimentaire.',
    'bi-flower1'
),
(
    'Industrie',
    'industrie',
    'Projets industriels et activités de production.',
    'bi-building'
),
(
    'Technologies',
    'technologies',
    'Technologies, numérique et innovation.',
    'bi-cpu'
),
(
    'Tourisme',
    'tourisme',
    'Projets touristiques et hôteliers.',
    'bi-airplane'
),
(
    'Énergies',
    'energies',
    'Énergies renouvelables et transition énergétique.',
    'bi-lightning'
),
(
    'Transport',
    'transport',
    'Transport, logistique et infrastructures.',
    'bi-truck'
),
(
    'Santé',
    'sante',
    'Investissements dans le secteur de la santé.',
    'bi-heart-pulse'
),
(
    'Services',
    'services',
    'Services aux entreprises et aux particuliers.',
    'bi-briefcase'
);


-- ============================================================
-- 15. COMPTE ADMINISTRATEUR
-- ============================================================
-- Mot de passe temporaire :
-- Admin@123
--
-- IMPORTANT :
-- Le mot de passe doit idéalement être remplacé par un hash
-- généré avec password_hash() côté PHP.

INSERT INTO users
(
    nom,
    prenom,
    email,
    password,
    telephone,
    role,
    statut
)
VALUES
(
    'Administrateur',
    'AAPI',
    'admin@aapi.dz',
    '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llCqzQ9Y5F7L2wYQY6m',
    NULL,
    'admin',
    'actif'
);


-- ============================================================
-- 16. UTILISATEUR INVESTISSEUR DE TEST
-- ============================================================
-- Mot de passe temporaire :
-- Investor@123

INSERT INTO users
(
    nom,
    prenom,
    email,
    password,
    telephone,
    role,
    statut
)
VALUES
(
    'Benali',
    'Ahmed',
    'investisseur@aapi.dz',
    '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llCqzQ9Y5F7L2wYQY6m',
    '0550000000',
    'investisseur',
    'actif'
);


-- ============================================================
-- 17. PROFIL INVESTISSEUR DE TEST
-- ============================================================

INSERT INTO investor_profiles
(
    user_id,
    type_investisseur,
    nom_entreprise,
    wilaya,
    commune,
    adresse,
    secteur_activite,
    description
)
VALUES
(
    2,
    'personne_morale',
    'AAPI Investissement',
    'Alger',
    'Alger Centre',
    'Alger, Algérie',
    'Technologies',
    'Entreprise de démonstration pour le compte investisseur.'
);


-- ============================================================
-- 18. PROJETS DE DÉMONSTRATION
-- ============================================================

INSERT INTO projects
(
    user_id,
    titre,
    slug,
    description,
    wilaya,
    commune,
    montant_investissement,
    nombre_emplois,
    statut,
    image
)
VALUES
(
    2,
    'Centre technologique et numérique',
    'centre-technologique-numerique',
    'Projet de création d’un centre spécialisé dans les technologies numériques et les services innovants.',
    'Alger',
    'Alger Centre',
    25000000.00,
    45,
    'en_cours',
    NULL
),
(
    2,
    'Complexe agroalimentaire',
    'complexe-agroalimentaire',
    'Projet industriel destiné à la transformation et à la valorisation des produits agricoles.',
    'Blida',
    'Blida',
    50000000.00,
    80,
    'en_etude',
    NULL
),
(
    2,
    'Projet touristique',
    'projet-touristique',
    'Création d’un complexe touristique moderne.',
    'Oran',
    'Oran',
    75000000.00,
    120,
    'soumis',
    NULL
);


-- ============================================================
-- 19. LIAISON PROJETS / SECTEURS
-- ============================================================

INSERT INTO project_sectors
(
    project_id,
    sector_id
)
VALUES
(1, 3),
(2, 1),
(2, 2),
(3, 4);


-- ============================================================
-- 20. ANNONCES DE DÉMONSTRATION
-- ============================================================

INSERT INTO announcements
(
    titre,
    slug,
    contenu,
    statut,
    date_publication
)
VALUES
(
    'Ouverture de la plateforme investisseurs',
    'ouverture-plateforme-investisseurs',
    'La plateforme digitale destinée aux investisseurs est désormais disponible.',
    'publie',
    CURRENT_TIMESTAMP
),
(
    'Accompagnement des investisseurs',
    'accompagnement-investisseurs',
    'Découvrez les services et dispositifs disponibles pour accompagner vos projets d’investissement.',
    'publie',
    CURRENT_TIMESTAMP
);


-- ============================================================
-- 21. ACTUALITÉS DE DÉMONSTRATION
-- ============================================================

INSERT INTO news
(
    titre,
    slug,
    resume,
    contenu,
    statut,
    date_publication
)
VALUES
(
    'Développement de l’investissement en Algérie',
    'developpement-investissement-algerie',
    'Les opportunités d’investissement continuent de se développer.',
    'Présentation des nouvelles opportunités et perspectives pour les investisseurs en Algérie.',
    'publie',
    CURRENT_TIMESTAMP
),
(
    'Nouvelles opportunités sectorielles',
    'nouvelles-opportunites-sectorielles',
    'Découvrez les nouveaux secteurs offrant des possibilités d’investissement.',
    'Présentation des opportunités dans les différents secteurs économiques.',
    'publie',
    CURRENT_TIMESTAMP
);


-- ============================================================
-- 22. ÉVÉNEMENT DE DÉMONSTRATION
-- ============================================================

INSERT INTO events
(
    titre,
    description,
    lieu,
    adresse,
    date_debut,
    date_fin,
    statut
)
VALUES
(
    'Forum de l’investissement',
    'Rencontre entre investisseurs, entrepreneurs et acteurs économiques.',
    'Palais des Congrès',
    'Alger, Algérie',
    (CURRENT_TIMESTAMP + INTERVAL '30 days'),
    (CURRENT_TIMESTAMP + INTERVAL '30 days' + INTERVAL '8 hours'),
    'a_venir'
);


-- ============================================================
-- 23. NOTIFICATION DE DÉMONSTRATION
-- ============================================================

INSERT INTO notifications
(
    user_id,
    titre,
    message,
    type,
    lu
)
VALUES
(
    2,
    'Bienvenue sur votre espace investisseur',
    'Votre compte investisseur a été créé avec succès.',
    'success',
    0
);


-- ============================================================
-- 24. MESSAGE DE DÉMONSTRATION
-- ============================================================

INSERT INTO messages
(
    sender_id,
    receiver_id,
    sujet,
    contenu,
    lu
)
VALUES
(
    1,
    2,
    'Bienvenue',
    'Bienvenue dans votre espace investisseur AAPI.',
    0
);


-- ============================================================
-- FIN
-- ============================================================

SET FOREIGN_KEY_CHECKS = 1;
-- PostgreSQL indexes and identity sequence synchronization

CREATE INDEX idx_wilayas_statut ON wilayas (statut);
CREATE INDEX idx_users_role ON users (role);
CREATE INDEX idx_users_statut ON users (statut);
CREATE INDEX idx_sectors_status ON sectors (statut);
CREATE INDEX idx_projects_user ON projects (user_id);
CREATE INDEX idx_projects_status ON projects (statut);
CREATE INDEX idx_projects_wilaya ON projects (wilaya);
CREATE INDEX idx_investments_user ON investments (user_id);
CREATE INDEX idx_investments_project ON investments (project_id);
CREATE INDEX idx_investments_status ON investments (statut);
CREATE INDEX idx_requests_user ON investment_requests (user_id);
CREATE INDEX idx_requests_project ON investment_requests (projet_id);
CREATE INDEX idx_requests_status ON investment_requests (statut);
CREATE INDEX idx_requests_priority ON investment_requests (priorite);
CREATE INDEX idx_documents_user ON documents (user_id);
CREATE INDEX idx_documents_project ON documents (project_id);
CREATE INDEX idx_documents_request ON documents (request_id);
CREATE INDEX idx_messages_sender ON messages (sender_id);
CREATE INDEX idx_messages_receiver ON messages (receiver_id);
CREATE INDEX idx_messages_read ON messages (lu);
CREATE INDEX idx_notifications_user ON notifications (user_id);
CREATE INDEX idx_notifications_read ON notifications (lu);
CREATE INDEX idx_news_status ON news (statut);
CREATE INDEX idx_news_date ON news (date_publication);
CREATE INDEX idx_announcements_status ON announcements (statut);
CREATE INDEX idx_announcements_date ON announcements (date_publication);
CREATE INDEX idx_events_start ON events (date_debut);
CREATE INDEX idx_events_status ON events (statut);

SELECT setval(pg_get_serial_sequence('users','id'), COALESCE(MAX(id),1), MAX(id) IS NOT NULL) FROM users;
SELECT setval(pg_get_serial_sequence('investor_profiles','id'), COALESCE(MAX(id),1), MAX(id) IS NOT NULL) FROM investor_profiles;
SELECT setval(pg_get_serial_sequence('sectors','id'), COALESCE(MAX(id),1), MAX(id) IS NOT NULL) FROM sectors;
SELECT setval(pg_get_serial_sequence('projects','id'), COALESCE(MAX(id),1), MAX(id) IS NOT NULL) FROM projects;
SELECT setval(pg_get_serial_sequence('investments','id'), COALESCE(MAX(id),1), MAX(id) IS NOT NULL) FROM investments;
SELECT setval(pg_get_serial_sequence('investment_requests','id'), COALESCE(MAX(id),1), MAX(id) IS NOT NULL) FROM investment_requests;
SELECT setval(pg_get_serial_sequence('documents','id'), COALESCE(MAX(id),1), MAX(id) IS NOT NULL) FROM documents;
SELECT setval(pg_get_serial_sequence('messages','id'), COALESCE(MAX(id),1), MAX(id) IS NOT NULL) FROM messages;
SELECT setval(pg_get_serial_sequence('notifications','id'), COALESCE(MAX(id),1), MAX(id) IS NOT NULL) FROM notifications;
SELECT setval(pg_get_serial_sequence('news','id'), COALESCE(MAX(id),1), MAX(id) IS NOT NULL) FROM news;
SELECT setval(pg_get_serial_sequence('announcements','id'), COALESCE(MAX(id),1), MAX(id) IS NOT NULL) FROM announcements;
SELECT setval(pg_get_serial_sequence('events','id'), COALESCE(MAX(id),1), MAX(id) IS NOT NULL) FROM events;
