import { useCallback, useEffect, useState } from "react";
import type { FormEvent } from "react";
import { useTranslation } from "../../i18n/I18nProvider";
import { Pencil, Plus, RefreshCw, Search, Trash2, X } from "lucide-react";
import "../../styles/admin-opportunities.css";

const API="http://localhost/aapi-api/auth/admin/admin.php";
type Row=Record<string,any>;
const empty={secteur:"",icone:"bi-buildings",titre:"",wilaya:"",description:"",investissement:"",emplois:"",image:"",statut:"publie"};

export default function AdminOpportunitiesPage({userId}:{userId:number}){\n const { t, language } = useTranslation();
 const [rows,setRows]=useState<Row[]>([]),[search,setSearch]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[photo,setPhoto]=useState<File|null>(null),[editing,setEditing]=useState<Row|null>(null),[form,setForm]=useState(empty),[modalOpen,setModalOpen]=useState(false);
 const load=useCallback(async()=>{setLoading(true);try{const q=new URLSearchParams({action:"opportunities",user_id:String(userId)});if(search.trim())q.set("search",search.trim());const r=await fetch(API+"?"+q);const j=await r.json();if(!j.success)throw Error(j.message);setRows(j.opportunities??[]);setError("")}catch(e){setError(e instanceof Error?e.message:t("admin.data.loadError"))}finally{setLoading(false)}},[search,userId]);
 useEffect(()=>{void load()},[load]);
 const open=(r?:Row)=>{setEditing(r??null);setModalOpen(true);setForm(r?{secteur:r.secteur??"",icone:r.icone??"bi-buildings",titre:r.titre??"",wilaya:r.wilaya??"",description:r.description??"",investissement:r.investissement??"",emplois:r.emplois??"",image:r.image??"",statut:r.statut??"publie"}:empty);setPhoto(null)};
 const save=async(e:FormEvent)=>{e.preventDefault();setSaving(true);try{const fd=new FormData();fd.append("action",editing?"update_opportunity":"create_opportunity");fd.append("user_id",String(userId));if(editing)fd.append("id",String(editing.id));Object.entries(form).forEach(([k,v])=>fd.append(k,String(v)));if(photo)fd.append("image",photo);const r=await fetch(API,{method:"POST",body:fd});const j=await r.json();if(!j.success)throw Error(j.message);setEditing(null);setModalOpen(false);await load()}catch(e){setError(e instanceof Error?e.message:"Erreur d'enregistrement")}finally{setSaving(false)}};
 const remove=async(id:number)=>{if(!confirm(t("admin.data.opportunity.confirmDelete")))return;try{const r=await fetch(API,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"delete_opportunities",user_id:userId,record_id:id})});const j=await r.json();if(!j.success)throw Error(j.message);await load()}catch(e){setError(e instanceof Error?e.message:t("admin.data.opportunity.deleteError"))}};
 return <main className="admin-opportunities-page" dir={language === "ar" ? "rtl" : "ltr"}>
  <div className="admin-opportunities-head"><div><span>AAPI • {t("admin.data.section.opportunities.title")}</span><h1>{t("admin.data.section.opportunities.title")}</h1><p>إدارة {t("admin.data.section.opportunities.title")} والصور والبيانات المعروضة في الموقع العام.</p></div><button onClick={()=>open()}><Plus size={17}/> {t("admin.data.opportunity.add")}</button></div>
  <div className="admin-opportunities-toolbar"><label><Search size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="{t("admin.data.opportunity.search")}" /></label><button onClick={()=>{setSearch("");void load()}}><RefreshCw size={15}/> {t("admin.data.reset")}</button></div>
  {error&&<div className="admin-opportunities-error">{error}</div>}
  {loading?<div className="admin-opportunities-empty">{t("admin.data.loading")}</div>:<div className="admin-opportunities-table-wrap"><table><thead><tr><th>{t("admin.data.labels.image")}</th><th>{t("admin.data.labels.secteur")}</th><th>{t("admin.data.labels.titre")}</th><th>{t("admin.data.labels.wilaya")}</th><th>{t("admin.data.labels.montant")}</th><th>{t("admin.data.opportunity.jobs")}</th><th>{t("admin.data.labels.statut")}</th><th>{t("admin.data.action")}</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><img src={r.image_url} alt="" /></td><td>{r.secteur}</td><td>{r.titre}</td><td>{r.wilaya}</td><td>{r.investissement}</td><td>{r.emplois}</td><td><span className={"admin-opportunity-status "+r.statut}>{r.statut==="publie"?"{t("admin.data.announcement.published")}":r.statut==="brouillon"?"{t("admin.data.announcement.draft")}":"{t("admin.data.announcement.archived")}"}</span></td><td><div className="admin-opportunity-actions"><button onClick={()=>open(r)}><Pencil size={15}/> {t("admin.data.opportunity.edit")}</button><button className="danger" onClick={()=>void remove(Number(r.id))}><Trash2 size={15}/> {t("admin.data.opportunity.delete")}</button></div></td></tr>)}</tbody></table></div>}
  {modalOpen&&<div className="admin-opportunity-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setModalOpen(false)}}><form className="admin-opportunity-modal" onSubmit={save}><header><div><span>{editing ? "{t("admin.data.opportunity.edit")} الفرصة" : "{t("admin.data.opportunity.new")}"}</span><h2>{editing ? "{t("admin.data.opportunity.edit")} فرصة استثمارية" : "{t("admin.data.opportunity.add")} استثمارية"}</h2></div><button type="button" onClick={()=>setModalOpen(false)}><X size={19}/></button></header><div className="admin-opportunity-form-grid">
 {([["secteur","{t("admin.data.labels.secteur")}"],["titre","{t("admin.data.labels.titre")}"],["wilaya","{t("admin.data.labels.wilaya")}"],["investissement","حجم {t("admin.data.labels.montant")}"],["emplois","{t("admin.data.opportunity.jobs")}"],["icone","{t("admin.data.opportunity.icon")}"]] as const).map(([k,l])=><label key={k}><span>{l}</span><input value={String(form[k])} onChange={e=>setForm(v=>({...v,[k]:e.target.value}))} required /></label>)}
 <label><span>{t("admin.data.labels.statut")}</span><select value={form.statut} onChange={e=>setForm(v=>({...v,statut:e.target.value}))}><option value="publie">{t("admin.data.announcement.published")}</option><option value="brouillon">{t("admin.data.announcement.draft")}</option><option value="archive">{t("admin.data.announcement.archived")}</option></select></label>
 <label className="full"><span>{t("admin.data.labels.image")}</span><input type="file" accept="image/png,image/jpeg,image/webp,image/gif" onChange={e=>setPhoto(e.target.files?.[0]??null)}/></label>
 <label className="full"><span>رابط {t("admin.data.labels.image")} (اختياري)</span><input value={form.image} onChange={e=>setForm(v=>({...v,image:e.target.value}))}/></label>
 <label className="full"><span>{t("admin.data.labels.description")}</span><textarea value={form.description} onChange={e=>setForm(v=>({...v,description:e.target.value}))} required/></label>
 </div><footer><button type="button" onClick={()=>setModalOpen(false)}>{t("admin.data.opportunity.cancel")}</button><button className="primary" disabled={saving}>{saving?<><RefreshCw size={15} className="spin"/> {t("admin.data.opportunity.saving")}</>:<><Pencil size={15}/> {t("admin.data.opportunity.save")}</>}</button></footer></form></div>}
 </main>;
}