import { useCallback, useEffect, useState } from "react";
import { Pencil, Plus, RefreshCw, Search, Trash2, X } from "lucide-react";
import "../../styles/admin-opportunities.css";

const API="http://localhost/aapi-api/auth/admin/admin.php";
type Row=Record<string,any>;
const empty={secteur:"",icone:"bi-buildings",titre:"",wilaya:"",description:"",investissement:"",emplois:"",image:"",statut:"publie"};

export default function AdminOpportunitiesPage({userId}:{userId:number}){
 const [rows,setRows]=useState<Row[]>([]),[search,setSearch]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[photo,setPhoto]=useState<File|null>(null),[editing,setEditing]=useState<Row|null>(null),[form,setForm]=useState(empty);
 const load=useCallback(async()=>{setLoading(true);try{const q=new URLSearchParams({action:"opportunities",user_id:String(userId)});if(search.trim())q.set("search",search.trim());const r=await fetch(API+"?"+q);const j=await r.json();if(!j.success)throw Error(j.message);setRows(j.opportunities??[]);setError("")}catch(e){setError(e instanceof Error?e.message:"Erreur de chargement")}finally{setLoading(false)}},[search,userId]);
 useEffect(()=>{void load()},[load]);
 const open=(r?:Row)=>{setEditing(r??null);setForm(r?{secteur:r.secteur??"",icone:r.icone??"bi-buildings",titre:r.titre??"",wilaya:r.wilaya??"",description:r.description??"",investissement:r.investissement??"",emplois:r.emplois??"",image:r.image??"",statut:r.statut??"publie"}:empty);setPhoto(null)};
 const save=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);try{const fd=new FormData();fd.append("action",editing?"update_opportunity":"create_opportunity");fd.append("user_id",String(userId));if(editing)fd.append("id",String(editing.id));Object.entries(form).forEach(([k,v])=>fd.append(k,String(v)));if(photo)fd.append("image",photo);const r=await fetch(API,{method:"POST",body:fd});const j=await r.json();if(!j.success)throw Error(j.message);setEditing(null);await load()}catch(e){setError(e instanceof Error?e.message:"Erreur d'enregistrement")}finally{setSaving(false)}};
 const remove=async(id:number)=>{if(!confirm("Supprimer cette opportunité ?"))return;try{const r=await fetch(API,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"delete_opportunities",user_id:userId,record_id:id})});const j=await r.json();if(!j.success)throw Error(j.message);await load()}catch(e){setError(e instanceof Error?e.message:"Erreur de suppression")}};
 return <main className="admin-opportunities-page" dir="rtl">
  <div className="admin-opportunities-head"><div><span>AAPI • OPPORTUNITÉS</span><h1>فرص الاستثمار</h1><p>إدارة فرص الاستثمار والصور والبيانات المعروضة في الموقع العام.</p></div><button onClick={()=>open()}><Plus size={17}/> إضافة فرصة</button></div>
  <div className="admin-opportunities-toolbar"><label><Search size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="ابحث في الفرص..." /></label><button onClick={()=>{setSearch("");void load()}}><RefreshCw size={15}/> إعادة ضبط</button></div>
  {error&&<div className="admin-opportunities-error">{error}</div>}
  {loading?<div className="admin-opportunities-empty">جاري تحميل البيانات...</div>:<div className="admin-opportunities-table-wrap"><table><thead><tr><th>الصورة</th><th>القطاع</th><th>العنوان</th><th>الولاية</th><th>الاستثمار</th><th>مناصب العمل</th><th>الحالة</th><th>الإجراء</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><img src={r.image_url} alt="" /></td><td>{r.secteur}</td><td>{r.titre}</td><td>{r.wilaya}</td><td>{r.investissement}</td><td>{r.emplois}</td><td><span className={"admin-opportunity-status "+r.statut}>{r.statut==="publie"?"منشور":r.statut==="brouillon"?"مسودة":"مؤرشف"}</span></td><td><div className="admin-opportunity-actions"><button onClick={()=>open(r)}><Pencil size={15}/> تعديل</button><button className="danger" onClick={()=>void remove(Number(r.id))}><Trash2 size={15}/> حذف</button></div></td></tr>)}</tbody></table></div>}
  {editing!==null&&<div className="admin-opportunity-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setEditing(null)}}><form className="admin-opportunity-modal" onSubmit={save}><header><div><span>{editing.id?"تعديل الفرصة":"فرصة جديدة"}</span><h2>{editing.id?"تعديل فرصة استثمارية":"إضافة فرصة استثمارية"}</h2></div><button type="button" onClick={()=>setEditing(null)}><X size={19}/></button></header><div className="admin-opportunity-form-grid">
 {([["secteur","القطاع"],["titre","العنوان"],["wilaya","الولاية"],["investissement","حجم الاستثمار"],["emplois","مناصب العمل"],["icone","أيقونة Bootstrap"]] as const).map(([k,l])=><label key={k}><span>{l}</span><input value={String(form[k])} onChange={e=>setForm(v=>({...v,[k]:e.target.value}))} required /></label>)}
 <label><span>الحالة</span><select value={form.statut} onChange={e=>setForm(v=>({...v,statut:e.target.value}))}><option value="publie">منشور</option><option value="brouillon">مسودة</option><option value="archive">مؤرشف</option></select></label>
 <label className="full"><span>الصورة</span><input type="file" accept="image/png,image/jpeg,image/webp,image/gif" onChange={e=>setPhoto(e.target.files?.[0]??null)}/></label>
 <label className="full"><span>رابط الصورة (اختياري)</span><input value={form.image} onChange={e=>setForm(v=>({...v,image:e.target.value}))}/></label>
 <label className="full"><span>الوصف</span><textarea value={form.description} onChange={e=>setForm(v=>({...v,description:e.target.value}))} required/></label>
 </div><footer><button type="button" onClick={()=>setEditing(null)}>إلغاء</button><button className="primary" disabled={saving}>{saving?<><RefreshCw size={15} className="spin"/> جاري الحفظ...</>:<><Pencil size={15}/> حفظ</>}</button></footer></form></div>}
 </main>;
}