import {useCallback,useEffect,useState} from "react";

const API="http://localhost/aapi-api/auth/admin/admin.php";
type R=Record<string,any>;
type Section="users"|"investors"|"projects"|"investments"|"requests"|"messages"|"documents";

const labels:Record<string,string>={brouillon:"مسودة",soumis:"مُرسل",en_etude:"قيد الدراسة",approuve:"مقبول",en_cours:"قيد التنفيذ",realise:"منجز",rejete:"مرفوض",archive:"مؤرشف",actif:"نشط",inactif:"غير نشط",suspendu:"موقوف",en_attente:"في الانتظار",valide:"مقبول",termine:"منتهي",annule:"ملغى",nouvelle:"جديد",acceptee:"مقبول",refusee:"مرفوض",terminee:"منتهٍ",lu:"مقروء",non_lu:"غير مقروء"};
const projectStatuses=["brouillon","soumis","en_etude","approuve","en_cours","realise","rejete","archive"];
const userStatuses=["actif","inactif","suspendu"];
const investmentStatuses=["en_attente","valide","en_cours","termine","annule"];
const requestStatuses=["nouvelle","en_cours","en_attente","acceptee","refusee","terminee"];
const documentStatuses=["en_attente","valide","rejete"];
const text=(v:any)=>labels[String(v??"")]??String(v??"—").replaceAll("_"," ");
const fmt=(v:any)=>Number(v??0).toLocaleString("fr-DZ");
const da=(v:any)=>`${fmt(v)} DA`;
const userIdOf=(r:R)=>r.user_id??r.investor_id??r.investisseur_id??r.utilisateur_id??"—";

export default function AdminDataPage({section,userId}:{section:Section;userId:number}){
 const cfg:Record<Section,{title:string;subtitle:string;action:string}>={users:{title:"المستخدمون",subtitle:"إدارة حسابات مستخدمي المنصة",action:"users"},investors:{title:"المستثمرون",subtitle:"إدارة ملفات المستثمرين",action:"investors"},projects:{title:"المشاريع",subtitle:"متابعة ومراجعة مشاريع الاستثمار",action:"projects"},investments:{title:"الاستثمارات",subtitle:"متابعة عمليات الاستثمار",action:"investments"},requests:{title:"الطلبات",subtitle:"متابعة طلبات المستثمرين وتحديث حالتها",action:"requests"},messages:{title:"الرسائل",subtitle:"إدارة رسائل المستثمرين ومتابعة المقروء وغير المقروء",action:"messages"},documents:{title:"الوثائق",subtitle:"مراجعة وثائق المستثمرين والتحقق من حالتها",action:"documents"}};
 const c=cfg[section],[rows,setRows]=useState<R[]>([]),[stats,setStats]=useState<R>({}),[loading,setLoading]=useState(true),[error,setError]=useState(""),[search,setSearch]=useState(""),[filter,setFilter]=useState("all"),[saving,setSaving]=useState<number|null>(null);
 const load=useCallback(async()=>{setLoading(true);try{const q=new URLSearchParams({action:c.action,user_id:String(userId)});if(search)q.set("search",search);if(filter!=="all")q.set("statut",filter);const r=await fetch(`${API}?${q}`),j=await r.json();if(!j.success)throw Error(j.message||"تعذر تحميل البيانات");setRows(Array.isArray(j[section])?j[section]:[]);setStats(j.stats??{});setError("")}catch(e){setError(e instanceof Error?e.message:"حدث خطأ")}finally{setLoading(false)}},[c.action,filter,search,section,userId]);
 useEffect(()=>{void load()},[load]);
 const options=section==="users"||section==="investors"?userStatuses:section==="projects"?projectStatuses:section==="investments"?investmentStatuses:section==="requests"?requestStatuses:section==="documents"?documentStatuses:[];
 const update=async(row:R,status:string)=>{const id=Number(row.id);if(!id)return;let action="";const body:R={user_id:userId};if(section==="users"){action="update_user_status";body.target_user_id=id}else if(section==="investors"){action="update_investor_status";body.target_user_id=id}else if(section==="projects"){action="update_project_status";body.project_id=id}else if(section==="investments"){action="update_investment_status";body.investment_id=id}else if(section==="requests"){action="update_request_status";body.request_id=id}else if(section==="documents"){action="update_document_status";body.document_id=id}else return;body.action=action;body.statut=status;setSaving(id);try{const r=await fetch(API,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),j=await r.json();if(!j.success)throw Error(j.message||"تعذر تحديث الحالة");setRows(prev=>prev.map(x=>x.id===row.id?{...x,statut:status}:x));setError("")}catch(e){setError(e instanceof Error?e.message:"تعذر تحديث الحالة")}finally{setSaving(null)}};
 const toggleMessage=async(row:R)=>{const id=Number(row.id);if(!id)return;const read=row.lu===1||row.lu===true||row.statut==="lu";const action=read?"mark_message_unread":"mark_message_read";setSaving(id);try{const r=await fetch(API,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({user_id:userId,action,message_id:id})}),j=await r.json();if(!j.success)throw Error(j.message||"تعذر تحديث الرسالة");setRows(prev=>prev.map(x=>x.id===row.id?{...x,lu:read?0:1,statut:read?"non_lu":"lu"}:x));setError("")}catch(e){setError(e instanceof Error?e.message:"تعذر تحديث الرسالة")}finally{setSaving(null)}};
 const keys=section==="projects"?["id","user_id","titre","wilaya","statut","montant_investissement"]:(rows[0]?Object.keys(rows[0]).filter(k=>!["created_at","updated_at"].includes(k)).slice(0,6):[]);
 return <div className="admin-dashboard"><header className="admin-dashboard-header"><div className="admin-dashboard-header-content"><div className="admin-dashboard-welcome"><span className="admin-dashboard-eyebrow">AAPI / ADMIN</span><h1>{c.title}</h1><p>{c.subtitle}</p></div><button className="admin-refresh-button" onClick={()=>void load()} disabled={loading}>↻ تحديث</button></div></header>{error&&<div className="admin-dashboard-error"><span>{error}</span></div>}<main className="admin-dashboard-main"><section className="admin-panel"><div className="admin-panel-header"><h2>{c.title}</h2><span>{fmt(stats.total??rows.length)} عنصر</span></div><div className="admin-toolbar"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="بحث..."/><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">كل الحالات</option>{options.map(o=><option key={o} value={o}>{text(o)}</option>)}</select></div>{loading?<div className="admin-empty-state">جاري التحميل...</div>:rows.length===0?<div className="admin-empty-state">لا توجد بيانات.</div>:<div className="admin-project-table-wrapper"><table className="admin-project-table"><thead><tr>{keys.map(k=><th key={k}>{k==="user_id"?"User ID":k==="titre"?"المشروع":k==="id"?"ID":text(k)}</th>)}{options.length>0&&<th>الإجراء</th>}{section==="messages"&&<th>القراءة</th>}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id??i}>{keys.map(k=><td key={k}>{k==="user_id"?userIdOf(r):k==="statut"?<span className={`admin-status-badge status-${r[k]}`}>{text(r[k])}</span>:k.includes("montant")||k.includes("investissement")?da(r[k]):String(r[k]??"—")}</td>)}{options.length>0&&<td><select className="status-select" value={String(r.statut??"")} disabled={saving===Number(r.id)} onChange={e=>void update(r,e.target.value)}><option value="">—</option>{options.map(o=><option key={o} value={o}>{text(o)}</option>)}</select></td>}{section==="messages"&&<td><button className={`admin-read-toggle ${(r.lu===1||r.lu===true||r.statut==="lu")?"is-read":"is-unread"}`} disabled={saving===Number(r.id)} onClick={()=>void toggleMessage(r)}>{r.lu===1||r.lu===true||r.statut==="lu"?"تعيين كغير مقروء":"تعيين كمقروء"}</button></td>}</tr>)}</tbody></table></div>}</section></main></div>;
}
