import type {ReactNode} from "react";
import {NavLink,useNavigate} from "react-router-dom";
import {Building2,ClipboardList,FileCheck2,FolderKanban,LayoutDashboard,LogOut,Menu,MessageSquare,Settings,UserCheck,Users,Wallet,X} from "lucide-react";

type R=Record<string,any>;
const getUser=():R|null=>{try{const x=localStorage.getItem("aapi_user"),u=x?JSON.parse(x):null;return u&&typeof u==="object"?u:null}catch{return null}};

export default function AdminNavbar({onToggle}:{onToggle:()=>void}){
 const nav=useNavigate(),u=getUser()??{};
 const items:Array<[string,string,ReactNode]>=[["/admin/dashboard","لوحة التحكم",<LayoutDashboard size={18}/>],["/admin/users","المستخدمون",<Users size={18}/>],["/admin/investors","المستثمرون",<UserCheck size={18}/>],["/admin/projects","المشاريع",<FolderKanban size={18}/>],["/admin/investments","الاستثمارات",<Wallet size={18}/>],["/admin/requests","الطلبات",<ClipboardList size={18}/>],["/admin/messages","الرسائل",<MessageSquare size={18}/>],["/admin/documents","الوثائق",<FileCheck2 size={18}/>]];
 const logout=()=>{localStorage.removeItem("aapi_user");nav("/login",{replace:true})};
 return <><div className="admin-mobile-header"><button className="admin-mobile-menu-button" onClick={onToggle}><Menu size={20}/></button><strong>AAPI</strong></div><aside className="admin-navbar"><div className="admin-navbar-brand"><button className="admin-navbar-brand-button" onClick={()=>nav("/admin/dashboard")}><span className="admin-navbar-logo">A</span><span className="admin-navbar-brand-text"><strong>AAPI</strong><small>الإدارة المركزية</small></span></button><button className="admin-navbar-mobile-close" onClick={onToggle}><X size={18}/></button></div><div className="admin-navbar-user"><span className="admin-navbar-user-avatar">{String(u.prenom??u.nom??"A").slice(0,2).toUpperCase()}</span><span className="admin-navbar-user-info"><strong>{`${u.prenom??""} ${u.nom??""}`.trim()||u.email||"Administrateur"}</strong><span>مسؤول النظام</span></span></div><nav className="admin-navbar-menu"><div className="admin-navbar-section"><div className="admin-navbar-section-title">الإدارة</div><div className="admin-navbar-section-items">{items.map(([to,n,icon])=><NavLink key={to} to={to} className={({isActive})=>`admin-nav-link${isActive?" active":""}`}><span className="admin-nav-icon">{icon}</span><span className="admin-nav-label">{n}</span></NavLink>)}</div></div><div className="admin-navbar-section"><div className="admin-navbar-section-title">النظام</div><NavLink to="/admin/settings" className={({isActive})=>`admin-nav-link${isActive?" active":""}`}><span className="admin-nav-icon"><Settings size={18}/></span><span className="admin-nav-label">الإعدادات</span></NavLink></div></nav><div className="admin-navbar-bottom"><button className="admin-navbar-bottom-button" onClick={()=>nav("/")}><Building2 size={17}/> الموقع العام</button><button className="admin-navbar-bottom-button admin-navbar-logout" onClick={logout}><LogOut size={17}/> تسجيل الخروج</button></div></aside></>;
}
