import { Link } from "react-router-dom";
import { useTranslation } from "../i18n/I18nProvider";

const copy = {
  ar:{overline:"الوكالة",title:"وكالة متخصصة في",titleStrong:"دعم وتطوير الاستثمار",description:"نعمل على توفير بيئة مناسبة للمستثمرين ومرافقة المشاريع الاستثمارية من الفكرة إلى الإنجاز.",breadcrumb:"الوكالة",introOverline:"من نحن",introTitle:"شريكك في",introTitleStrong:"رحلة الاستثمار",introText1:"تمثل الوكالة فضاءً مؤسساتيًا يهدف إلى تسهيل وتطوير الاستثمار، من خلال توفير المعلومات الضرورية ومرافقة المستثمرين وأصحاب المشاريع.",introText2:"نحرص على تعزيز التواصل مع المستثمرين وتوجيههم نحو الفرص المتاحة، مع العمل على تحسين جودة الخدمات وتبسيط الإجراءات المرتبطة بالمشاريع الاستثمارية.",investorServices:"تعرف على خدمات المستثمر",vision:"رؤية مؤسساتية",visionTitle:"نحو بيئة استثمارية أكثر",visionStrong:"تنافسية واستدامة",visionText:"نساهم في خلق مناخ أعمال يساعد على إطلاق المشاريع وتوسيع الاستثمارات ودعم التنمية الاقتصادية.",supportInvestor:"دعم المستثمر",mission:"مهمتنا",missionTitle:"ماذا نقدم",missionStrong:"للمستثمر؟",missionText:"مجموعة من الخدمات التي تهدف إلى تسهيل الوصول إلى المعلومات والفرص الاستثمارية.",infoTitle:"توفير المعلومات",infoText:"توفير معلومات واضحة حول القطاعات والفرص والمشاريع الاستثمارية المتاحة.",supportTitle:"مرافقة المستثمر",supportText:"توجيه المستثمر ومرافقته خلال مختلف مراحل تطوير مشروعه الاستثماري.",developmentTitle:"تطوير الاستثمار",developmentText:"المساهمة في تعزيز المشاريع ورفع جاذبية القطاعات الاستثمارية.",values:"قيمنا",valuesTitle:"مبادئنا أساس",valuesStrong:"نجاحنا",valuesText:"نعمل وفق مجموعة من المبادئ التي تضع المستثمر وجودة الخدمة في صميم عملنا.",trust:"الثقة",trustText:"علاقة مؤسساتية مبنية على الثقة.",efficiency:"الفعالية",efficiencyText:"خدمات عملية وسريعة للمستثمر.",partnership:"الشراكة",partnershipText:"التعاون مع المستثمرين وأصحاب المشاريع.",sustainability:"الاستدامة",sustainabilityText:"دعم استثمارات طويلة المدى.",opportunities:"فرص الاستثمار",ctaTitle:"هل لديك مشروع استثماري؟",ctaText:"اكتشف القطاعات والفرص المتاحة وابدأ رحلتك الاستثمارية.",discover:"اكتشف الفرص"},
  fr:{overline:"L’Agence",title:"Une agence spécialisée dans",titleStrong:"le soutien et le développement de l’investissement",description:"Nous créons un environnement favorable aux investisseurs et accompagnons les projets d’investissement de l’idée à la réalisation.",breadcrumb:"L’Agence",introOverline:"Qui sommes-nous ?",introTitle:"Votre partenaire dans",introTitleStrong:"le parcours d’investissement",introText1:"L’Agence constitue un espace institutionnel dédié à la facilitation et au développement de l’investissement, en fournissant les informations nécessaires et en accompagnant les investisseurs et porteurs de projets.",introText2:"Nous renforçons le dialogue avec les investisseurs et les orientons vers les opportunités disponibles, tout en améliorant la qualité des services et en simplifiant les procédures liées aux projets d’investissement.",investorServices:"Découvrir les services aux investisseurs",vision:"Vision institutionnelle",visionTitle:"Vers un environnement d’investissement plus",visionStrong:"compétitif et durable",visionText:"Nous contribuons à créer un climat d’affaires favorable au lancement des projets, à l’expansion des investissements et au développement économique.",supportInvestor:"Soutenir l’investisseur",mission:"Notre mission",missionTitle:"Que proposons-nous",missionStrong:"à l’investisseur ?",missionText:"Un ensemble de services visant à faciliter l’accès aux informations et aux opportunités d’investissement.",infoTitle:"Fournir l’information",infoText:"Fournir des informations claires sur les secteurs, opportunités et projets d’investissement disponibles.",supportTitle:"Accompagner l’investisseur",supportText:"Orienter et accompagner l’investisseur à toutes les étapes du développement de son projet.",developmentTitle:"Développer l’investissement",developmentText:"Contribuer au renforcement des projets et à l’attractivité des secteurs d’investissement.",values:"Nos valeurs",valuesTitle:"Nos principes sont la base de",valuesStrong:"notre réussite",valuesText:"Nous agissons selon des principes qui placent l’investisseur et la qualité du service au cœur de notre action.",trust:"Confiance",trustText:"Une relation institutionnelle fondée sur la confiance.",efficiency:"Efficacité",efficiencyText:"Des services pratiques et rapides pour l’investisseur.",partnership:"Partenariat",partnershipText:"Coopération avec les investisseurs et porteurs de projets.",sustainability:"Durabilité",sustainabilityText:"Soutenir les investissements à long terme.",opportunities:"Opportunités d’investissement",ctaTitle:"Vous avez un projet d’investissement ?",ctaText:"Découvrez les secteurs et opportunités disponibles et commencez votre parcours d’investissement.",discover:"Découvrir les opportunités"},
  en:{overline:"The Agency",title:"An agency specialized in",titleStrong:"supporting and developing investment",description:"We provide a favorable environment for investors and support investment projects from idea to completion.",breadcrumb:"The Agency",introOverline:"About us",introTitle:"Your partner in",introTitleStrong:"the investment journey",introText1:"The Agency is an institutional space dedicated to facilitating and developing investment by providing essential information and supporting investors and project owners.",introText2:"We strengthen communication with investors and guide them toward available opportunities while improving service quality and simplifying investment procedures.",investorServices:"Discover investor services",vision:"Institutional vision",visionTitle:"Towards a more",visionStrong:"competitive and sustainable investment environment",visionText:"We help create a business climate that supports project launches, investment expansion and economic development.",supportInvestor:"Investor support",mission:"Our mission",missionTitle:"What do we offer",missionStrong:"investors?",missionText:"A range of services designed to facilitate access to investment information and opportunities.",infoTitle:"Providing information",infoText:"Providing clear information about available sectors, opportunities and investment projects.",supportTitle:"Supporting investors",supportText:"Guiding and supporting investors throughout the different stages of project development.",developmentTitle:"Developing investment",developmentText:"Contributing to stronger projects and more attractive investment sectors.",values:"Our values",valuesTitle:"Our principles are the foundation of",valuesStrong:"our success",valuesText:"We work according to principles that place investors and service quality at the heart of our mission.",trust:"Trust",trustText:"An institutional relationship built on trust.",efficiency:"Efficiency",efficiencyText:"Practical and fast services for investors.",partnership:"Partnership",partnershipText:"Cooperation with investors and project owners.",sustainability:"Sustainability",sustainabilityText:"Supporting long-term investments.",opportunities:"Investment opportunities",ctaTitle:"Do you have an investment project?",ctaText:"Discover the available sectors and opportunities and start your investment journey.",discover:"Discover opportunities"}
} as const;

function Agency() {
  const { language } = useTranslation();
  const c = copy[language];
  const home = language === "ar" ? "الرئيسية" : language === "fr" ? "Accueil" : "Home";
  const serviceCards = [["bi-info-circle",c.infoTitle,c.infoText],["bi-headset",c.supportTitle,c.supportText],["bi-graph-up-arrow",c.developmentTitle,c.developmentText]];
  const values = [["bi-shield-check",c.trust,c.trustText],["bi-lightning-charge",c.efficiency,c.efficiencyText],["bi-people",c.partnership,c.partnershipText],["bi-recycle",c.sustainability,c.sustainabilityText]];
  return <main className="agency-page">
    <section className="agency-hero"><div className="container"><div className="agency-hero-content"><span className="agency-overline">{c.overline}</span><h1>{c.title}<strong> {c.titleStrong}</strong></h1><p>{c.description}</p><div className="agency-breadcrumb"><Link to="/">{home}</Link><i className="bi bi-chevron-left" aria-hidden="true"/><span>{c.breadcrumb}</span></div></div></div></section>
    <section className="agency-introduction"><div className="container"><div className="row align-items-center g-5"><div className="col-lg-6"><div className="agency-section-heading"><span className="agency-section-overline">{c.introOverline}</span><h2>{c.introTitle}<strong> {c.introTitleStrong}</strong></h2></div><p className="agency-intro-text">{c.introText1}</p><p className="agency-intro-text">{c.introText2}</p><Link to="/investor" className="agency-primary-button">{c.investorServices}<i className="bi bi-arrow-left" aria-hidden="true"/></Link></div><div className="col-lg-6"><div className="agency-intro-card"><div className="agency-intro-card-icon"><i className="bi bi-buildings" aria-hidden="true"/></div><span>{c.vision}</span><h3>{c.visionTitle}<strong> {c.visionStrong}</strong></h3><p>{c.visionText}</p><div className="agency-card-line"/><div className="agency-card-number"><strong>01</strong><span>{c.supportInvestor}</span></div></div></div></div></div></section>
    <section className="agency-mission"><div className="container"><div className="agency-centered-heading"><span className="agency-section-overline">{c.mission}</span><h2>{c.missionTitle}<strong> {c.missionStrong}</strong></h2><p>{c.missionText}</p></div><div className="row g-4 agency-services-grid">{serviceCards.map(([icon,title,text],i)=><div className="col-lg-4 col-md-6" key={title}><div className="agency-service-card"><span className="agency-service-number">0{i+1}</span><div className="agency-service-icon"><i className={`bi ${icon}`} aria-hidden="true"/></div><h3>{title}</h3><p>{text}</p></div></div>)}</div></div></section>
    <section className="agency-values"><div className="container"><div className="row align-items-center g-5"><div className="col-lg-5"><span className="agency-section-overline">{c.values}</span><h2 className="agency-values-title">{c.valuesTitle}<strong> {c.valuesStrong}</strong></h2><p className="agency-values-text">{c.valuesText}</p></div><div className="col-lg-7"><div className="row g-3">{values.map(([icon,title,text])=><div className="col-md-6" key={title}><div className="agency-value-item"><i className={`bi ${icon}`} aria-hidden="true"/><div><h3>{title}</h3><p>{text}</p></div></div></div>)}</div></div></div></div></section>
    <section className="agency-final-cta"><div className="container"><div className="agency-final-cta-inner"><div><span>{c.opportunities}</span><h2>{c.ctaTitle}</h2><p>{c.ctaText}</p></div><Link to="/opportunities" className="agency-final-button">{c.discover}<i className="bi bi-arrow-left" aria-hidden="true"/></Link></div></div></section>
  </main>;
}

export default Agency;
