import { Link } from "react-router-dom";
import { useTranslation } from "../i18n/I18nProvider";

interface CardItem { icon: string; number?: string; title: string; text: string; }

function Investor() {
  const { t } = useTranslation();
  const services: CardItem[] = [
    { icon:"bi-person-workspace", number:"01", title:t("investorPage.service1"), text:t("investorPage.service1Text") },
    { icon:"bi-file-earmark-text", number:"02", title:t("investorPage.service2"), text:t("investorPage.service2Text") },
    { icon:"bi-graph-up-arrow", number:"03", title:t("investorPage.service3"), text:t("investorPage.service3Text") },
    { icon:"bi-headset", number:"04", title:t("investorPage.service4"), text:t("investorPage.service4Text") },
  ];
  const steps: CardItem[] = [
    { number:"01", icon:"bi-lightbulb", title:t("investorPage.step1"), text:t("investorPage.step1Text") },
    { number:"02", icon:"bi-search", title:t("investorPage.step2"), text:t("investorPage.step2Text") },
    { number:"03", icon:"bi-file-earmark-check", title:t("investorPage.step3"), text:t("investorPage.step3Text") },
    { number:"04", icon:"bi-building-check", title:t("investorPage.step4"), text:t("investorPage.step4Text") },
  ];
  const documents: CardItem[] = [
    { icon:"bi-file-earmark-pdf", title:t("investorPage.doc1"), text:t("investorPage.doc1Text") },
    { icon:"bi-journal-text", title:t("investorPage.doc2"), text:t("investorPage.doc2Text") },
    { icon:"bi-map", title:t("investorPage.doc3"), text:t("investorPage.doc3Text") },
    { icon:"bi-bar-chart", title:t("investorPage.doc4"), text:t("investorPage.doc4Text") },
  ];

  return <>
    <section className="inner-hero investor-inner-hero"><div className="container"><div className="inner-hero-content"><span>{t("investorPage.heroOverline")}</span><h1>{t("investorPage.heroTitle")}</h1><p>{t("investorPage.heroText")}</p></div></div></section>

    <section className="investor-intro"><div className="container"><div className="row align-items-center g-5"><div className="col-lg-7"><span className="section-overline">{t("investorPage.introOverline")}</span><h2 className="investor-main-title">{t("investorPage.introTitle")}<strong>{t("investorPage.introStrong")}</strong></h2><p className="investor-main-text">{t("investorPage.introText1")}</p><p className="investor-main-text">{t("investorPage.introText2")}</p><div className="investor-intro-actions"><Link to="/inscription" className="aapi-primary-button">{t("investorPage.register")} <i className="bi bi-person-plus" aria-hidden="true"/></Link><Link to="/opportunities" className="aapi-secondary-button">{t("investorPage.opportunities")} <i className="bi bi-arrow-left" aria-hidden="true"/></Link></div></div><div className="col-lg-5"><div className="investor-intro-card"><div className="investor-intro-card-icon"><i className="bi bi-briefcase" aria-hidden="true"/></div><span>{t("investorPage.space")}</span><strong>{t("investorPage.fromIdea")}<br/>{t("investorPage.toCompletion")}</strong><p>{t("investorPage.cardText")}</p><div className="investor-card-decoration"><i className="bi bi-arrow-up-left" aria-hidden="true"/></div></div></div></div></div></section>

    <section className="investor-services" id="investor-services"><div className="container"><div className="aapi-section-header centered"><span className="section-overline">{t("investorPage.servicesOverline")}</span><h2>{t("investorPage.servicesTitle")}<strong>{t("investorPage.servicesStrong")}</strong></h2><p>{t("investorPage.servicesText")}</p></div><div className="row g-4">{services.map((service)=><div className="col-xl-3 col-lg-6 col-md-6" key={service.number}><article className="investor-service-card"><div className="investor-service-top"><span>{service.number}</span><div className="investor-service-icon"><i className={`bi ${service.icon}`} aria-hidden="true"/></div></div><h3>{service.title}</h3><p>{service.text}</p><a href="#investor-steps">{t("investorPage.discover")} <i className="bi bi-arrow-left" aria-hidden="true"/></a></article></div>)}</div></div></section>

    <section className="investor-steps" id="investor-steps"><div className="container"><div className="row align-items-center g-5"><div className="col-lg-5"><span className="section-overline">{t("investorPage.stepsOverline")}</span><h2 className="investor-steps-title">{t("investorPage.stepsTitle")}<strong>{t("investorPage.stepsStrong")}</strong></h2><p className="investor-steps-intro">{t("investorPage.stepsText")}</p><Link to="/opportunities" className="aapi-primary-button">{t("investorPage.explore")} <i className="bi bi-arrow-left" aria-hidden="true"/></Link></div><div className="col-lg-7"><div className="row g-4 investor-steps-list">{steps.map((step)=><div className="col-xl-6 col-lg-6 col-md-6" key={step.number}><article className="investor-step-card"><div className="investor-step-top"><span>{step.number}</span><div className="investor-step-icon"><i className={`bi ${step.icon}`} aria-hidden="true"/></div></div><h3>{step.title}</h3><p>{step.text}</p></article></div>)}</div></div></div></div></section>

    <section className="investor-documents"><div className="container"><div className="aapi-section-header"><div><span className="section-overline">{t("investorPage.resourcesOverline")}</span><h2>{t("investorPage.resourcesTitle")}<strong>{t("investorPage.resourcesStrong")}</strong></h2></div><p>{t("investorPage.resourcesText")}</p></div><div className="row g-4">{documents.map((document)=><div className="col-lg-6" key={document.title}><article className="investor-document-card"><div className="investor-document-icon"><i className={`bi ${document.icon}`} aria-hidden="true"/></div><div className="investor-document-content"><h3>{document.title}</h3><p>{document.text}</p><a href="#">{t("investorPage.viewDocument")} <i className="bi bi-arrow-left" aria-hidden="true"/></a></div></article></div>)}</div></div></section>

    <section className="investor-faq" id="investor-faq"><div className="container"><div className="aapi-section-header centered"><span className="section-overline">{t("investorPage.faqOverline")}</span><h2>{t("investorPage.faqTitle")}<strong>{t("investorPage.faqStrong")}</strong></h2><p>{t("investorPage.faqText")}</p></div><div className="row justify-content-center"><div className="col-lg-9"><div className="accordion investor-accordion" id="investorAccordion"><div className="accordion-item"><h2 className="accordion-header"><button className="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#faqOne" aria-expanded="true" aria-controls="faqOne">{t("investorPage.faq1")}</button></h2><div id="faqOne" className="accordion-collapse collapse show" data-bs-parent="#investorAccordion"><div className="accordion-body">{t("investorPage.faq1Text")}</div></div></div><div className="accordion-item"><h2 className="accordion-header"><button className="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#faqTwo" aria-expanded="false" aria-controls="faqTwo">{t("investorPage.faq2")}</button></h2><div id="faqTwo" className="accordion-collapse collapse" data-bs-parent="#investorAccordion"><div className="accordion-body">{t("investorPage.faq2Text")}</div></div></div><div className="accordion-item"><h2 className="accordion-header"><button className="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#faqThree" aria-expanded="false" aria-controls="faqThree">{t("investorPage.faq3")}</button></h2><div id="faqThree" className="accordion-collapse collapse" data-bs-parent="#investorAccordion"><div className="accordion-body">{t("investorPage.faq3Text")}</div></div></div><div className="accordion-item"><h2 className="accordion-header"><button className="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#faqFour" aria-expanded="false" aria-controls="faqFour">{t("investorPage.faq4")}</button></h2><div id="faqFour" className="accordion-collapse collapse" data-bs-parent="#investorAccordion"><div className="accordion-body">{t("investorPage.faq4Text")}</div></div></div></div></div></div></div></section>

    <section className="investor-final-cta"><div className="container"><div className="investor-final-cta-inner"><div><span>{t("investorPage.finalOverline")}</span><h2>{t("investorPage.finalTitle")}</h2><p>{t("investorPage.finalText")}</p></div><div className="investor-final-actions"><Link to="/inscription" className="aapi-white-button">{t("investorPage.register")} <i className="bi bi-person-plus" aria-hidden="true"/></Link><Link to="/opportunities" className="aapi-outline-white-button">{t("investorPage.opportunities")} <i className="bi bi-arrow-left" aria-hidden="true"/></Link><Link to="/contact" className="aapi-outline-white-button">{t("common.contact")} <i className="bi bi-arrow-left" aria-hidden="true"/></Link></div></div></div></section>
  </>;
}

export default Investor;
