import { useEffect, useMemo, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { useTranslation } from "../i18n/I18nProvider";
import { newsDetailsTranslations } from "../i18n/newsDetailsTranslations";

type ApiNews={id:number;titre:string;resume:string|null;contenu:string;image:string|null;auteur:string|null;date_publication:string|null;created_at:string};
const API_URL="http://localhost/aapi-api/news.php";
function resolveNewsImage(image:string|null,id:number){if(!image)return null;const value=String(image).trim();if(!value)return null;if(/^https?:\/\//i.test(value))return value;return `http://localhost/aapi-api/news-image.php?id=${id}`;}

function NewsDetails(){
 const {id}=useParams<{id:string}>();const {language}=useTranslation();const page=newsDetailsTranslations[language].page;
 const [article,setArticle]=useState<ApiNews|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState("");
 useEffect(()=>{let cancelled=false;const load=async()=>{if(!id){setError(page.notFound);setLoading(false);return;}try{setLoading(true);setError("");const response=await fetch(`${API_URL}?id=${encodeURIComponent(id)}`);const data=await response.json();if(!response.ok||!data?.success||!data?.news)throw new Error(data?.message||page.notFound);if(!cancelled)setArticle({...data.news,image:resolveNewsImage(data.news.image,Number(data.news.id))});}catch(e){if(!cancelled){setArticle(null);setError(e instanceof Error?e.message:page.notFound);}}finally{if(!cancelled)setLoading(false);}};void load();return()=>{cancelled=true;};},[id,page.notFound]);
 const locale=language==="ar"?"ar-DZ":language==="fr"?"fr-DZ":"en-DZ";
 const formattedDate=useMemo(()=>{const date=article?.date_publication||article?.created_at;if(!date)return "";const parsed=new Date(date.replace(" ","T"));return Number.isNaN(parsed.getTime())?date:new Intl.DateTimeFormat(locale,{day:"2-digit",month:"long",year:"numeric"}).format(parsed);},[article,locale]);
 const paragraphs=useMemo(()=>article?.contenu?.split(/\r?\n\r?\n/).map(x=>x.trim()).filter(Boolean)??[],[article]);
 if(loading)return <section className="news-details-not-found"><div className="container"><div className="news-details-empty"><div className="news-details-empty-icon"><i className="bi bi-arrow-repeat" aria-hidden="true"/></div><h1>{page.details}</h1><p>...</p></div></div></section>;
 if(!article)return <section className="news-details-not-found"><div className="container"><div className="news-details-empty"><div className="news-details-empty-icon"><i className="bi bi-newspaper" aria-hidden="true"/></div><h1>{page.notFound}</h1><p>{error||page.notFoundText}</p><Link to="/news" className="aapi-primary-button">{page.back}<i className="bi bi-arrow-left" aria-hidden="true"/></Link></div></div></section>;
 return <><section className="inner-hero news-details-hero"><div className="container"><div className="inner-hero-content"><span>{page.agencyNews}</span><h1>{page.details}</h1><p>{formattedDate}</p></div></div></section><section className="news-details-section"><div className="container"><div className="row g-5"><div className="col-lg-8"><article className="news-details-article">
 {article.image?<div className="news-details-cover news-details-cover-image"><img src={article.image} alt={article.titre}/><span className="news-details-cover-category">{page.agencyNews}</span><div className="news-details-cover-date"><i className="bi bi-calendar3" aria-hidden="true"/>{formattedDate}</div></div>:<div className="news-details-cover"><div className="news-details-cover-pattern"/><div className="news-details-cover-icon"><i className="bi bi-newspaper" aria-hidden="true"/></div><span className="news-details-cover-category">{page.agencyNews}</span><div className="news-details-cover-date"><i className="bi bi-calendar3" aria-hidden="true"/>{formattedDate}</div></div>}
 <div className="news-details-content"><div className="news-details-meta"><span><i className="bi bi-newspaper" aria-hidden="true"/>{page.agencyNews}</span><span><i className="bi bi-calendar3" aria-hidden="true"/>{formattedDate}</span></div><h1>{article.titre}</h1>{article.resume&&<p className="news-details-summary">{article.resume}</p>}<div className="news-details-divider"/>{paragraphs.map((p,i)=><p key={`${article.id}-${i}`}>{p}</p>)}<div className="news-details-share"><span>{page.share}</span><div className="news-share-buttons"><button type="button" aria-label={page.facebook}><i className="bi bi-facebook" aria-hidden="true"/></button><button type="button" aria-label={page.x}><i className="bi bi-twitter-x" aria-hidden="true"/></button><button type="button" aria-label={page.linkedin}><i className="bi bi-linkedin" aria-hidden="true"/></button></div></div></div></article></div><div className="col-lg-4"><aside className="news-details-sidebar"><div className="news-sidebar-card"><div className="news-sidebar-icon"><i className="bi bi-newspaper" aria-hidden="true"/></div><h3>{page.media}</h3><p>{page.mediaText}</p><Link to="/news" className="news-sidebar-link">{page.allNews}<i className="bi bi-arrow-left" aria-hidden="true"/></Link></div><div className="news-sidebar-card news-sidebar-green"><span>{page.investment}</span><h3>{page.investmentTitle}</h3><p>{page.investmentText}</p><Link to="/opportunities" className="aapi-white-button">{page.discover}<i className="bi bi-arrow-left" aria-hidden="true"/></Link></div><div className="news-sidebar-card"><h3>{page.help}</h3><p>{page.helpText}</p><Link to="/contact" className="news-sidebar-contact">{page.contact}<i className="bi bi-arrow-left" aria-hidden="true"/></Link></div></aside></div></div></div></section><section className="news-details-bottom"><div className="container"><Link to="/news" className="news-back-button"><i className="bi bi-arrow-right" aria-hidden="true"/>{page.backAll}</Link></div></section></>;
}
export default NewsDetails;
