import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { useTranslation } from "../i18n/I18nProvider";

type NewsItem = { id:number; title:string; excerpt:string; date:string|null; image:string|null; category:string; featured?:boolean };
type ApiNews = { id:number; titre:string; resume:string|null; contenu:string; image:string|null; date_publication:string|null; created_at:string };
const API_URL="http://localhost/aapi-api/news.php";

function resolveNewsImage(image:string|null|undefined,id:number){
  if(!image)return null;
  const value=String(image).trim();
  if(!value)return null;
  if(/^https?:\/\//i.test(value))return value;
  return `http://localhost/aapi-api/news-image.php?id=${id}`;
}

const copy={
  ar:{over:"المركز الإعلامي",title:"الأخبار",hero:"تابع آخر الأخبار والمستجدات المتعلقة بالاستثمار وخدمات الوكالة.",featured:"خبر مميز",latest:"آخر الأخبار",strong:" مستجداتنا",intro:"اكتشف آخر الأخبار والأنشطة والمستجدات المرتبطة بالاستثمار وخدمات المستثمرين.",search:"ابحث في الأخبار...",all:"الكل",count:"أخبار",reset:"إعادة ضبط البحث",more:"قراءة المزيد",empty:"لم يتم العثور على نتائج",emptyText:"لم نجد أخبارًا مطابقة لبحثك الحالي.",show:"عرض جميع الأخبار",stay:"ابقَ على اطلاع",cta:"تابع آخر مستجدات الاستثمار",ctaText:"اكتشف الأخبار والفعاليات والفرص الجديدة التي تهم المستثمرين.",category:"أخبار الوكالة",loading:"جاري تحميل الأخبار...",error:"تعذر تحميل الأخبار."},
  fr:{over:"Centre média",title:"Actualités",hero:"Suivez les dernières nouvelles et mises à jour liées à l'investissement et aux services de l'agence.",featured:"À la une",latest:"Dernières actualités",strong:" nos actualités",intro:"Découvrez les dernières nouvelles, activités et mises à jour liées à l'investissement et aux services aux investisseurs.",search:"Rechercher dans les actualités...",all:"Tous",count:"actualités",reset:"Réinitialiser la recherche",more:"Lire la suite",empty:"Aucun résultat trouvé",emptyText:"Aucune actualité ne correspond à votre recherche.",show:"Afficher toutes les actualités",stay:"Restez informé",cta:"Suivez les dernières actualités de l'investissement",ctaText:"Découvrez les nouvelles, événements et opportunités qui intéressent les investisseurs.",category:"Actualités de l'agence",loading:"Chargement des actualités...",error:"Impossible de charger les actualités."},
  en:{over:"Media center",title:"News",hero:"Follow the latest news and updates related to investment and agency services.",featured:"Featured news",latest:"Latest news",strong:" our updates",intro:"Discover the latest news, activities and updates related to investment and investor services.",search:"Search news...",all:"All",count:"news",reset:"Reset search",more:"Read more",empty:"No results found",emptyText:"No news matches your current search.",show:"Show all news",stay:"Stay informed",cta:"Follow the latest investment updates",ctaText:"Discover news, events and new opportunities that matter to investors.",category:"Agency news",loading:"Loading news...",error:"Unable to load news."}
} as const;

function NewsPage(){
  const {language}=useTranslation(); const c=copy[language];
  const [news,setNews]=useState<NewsItem[]>([]); const [active,setActive]=useState(c.all);
  const [search,setSearch]=useState(""); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
  useEffect(()=>setActive(c.all),[c.all]);
  useEffect(()=>{let cancelled=false;const load=async()=>{try{setLoading(true);setError("");const response=await fetch(API_URL);const data=await response.json();if(!response.ok||!data?.success)throw new Error(data?.message||c.error);const rows:ApiNews[]=Array.isArray(data.news)?data.news:[];if(!cancelled)setNews(rows.map((item,index)=>({id:Number(item.id),title:item.titre,excerpt:item.resume?.trim()||item.contenu,date:item.date_publication||item.created_at||null,image:resolveNewsImage(item.image,Number(item.id)),category:c.category,featured:index===0})));}catch(e){if(!cancelled){setNews([]);setError(e instanceof Error?e.message:c.error);}}finally{if(!cancelled)setLoading(false);}};void load();return()=>{cancelled=true;};},[c.category,c.error]);
  const locale=language==="ar"?"ar-DZ":language==="fr"?"fr-DZ":"en-DZ";
  const formatDate=(value:string|null)=>{if(!value)return "";const parsed=new Date(value.replace(" ","T"));return Number.isNaN(parsed.getTime())?value:new Intl.DateTimeFormat(locale,{day:"2-digit",month:"long",year:"numeric"}).format(parsed);};
  const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return news.filter(item=>(active===c.all||item.category===active)&&(!q||`${item.title} ${item.excerpt} ${item.category}`.toLowerCase().includes(q)));},[active,search,news,c.all]);
  const reset=()=>{setSearch("");setActive(c.all)}; const featured=news.find(x=>x.featured);
  return <><section className="inner-hero news-inner-hero"><div className="container"><div className="inner-hero-content"><span>{c.over}</span><h1>{c.title}</h1><p>{c.hero}</p></div></div></section>
  {featured&&<section className="news-featured-section"><div className="container"><div className="news-featured-card"><div className="row g-0 align-items-stretch"><div className="col-lg-6"><div className="news-featured-visual">{featured.image?<img src={featured.image} alt={featured.title}/>:<><div className="news-featured-pattern"/><div className="news-featured-icon"><i className="bi bi-newspaper" aria-hidden="true"/></div></>}<span className="news-featured-label">{c.featured}</span><div className="news-featured-date"><i className="bi bi-calendar3" aria-hidden="true"/>{formatDate(featured.date)}</div></div></div><div className="col-lg-6"><div className="news-featured-content"><span className="section-overline">{featured.category}</span><h2>{featured.title}</h2><p>{featured.excerpt}</p><div className="news-featured-meta"><span><i className="bi bi-newspaper" aria-hidden="true"/>{c.latest}</span><span><i className="bi bi-calendar3" aria-hidden="true"/>{formatDate(featured.date)}</span></div><Link to={`/news/${featured.id}`} className="aapi-primary-button">{c.more}<i className="bi bi-arrow-left" aria-hidden="true"/></Link></div></div></div></div></div></section>}
  <section className="news-page-section"><div className="container"><div className="aapi-section-header"><div><span className="section-overline">{c.latest}</span><h2>{c.latest}<strong>{c.strong}</strong></h2></div><p>{c.intro}</p></div><div className="news-toolbar"><div className="news-search"><i className="bi bi-search" aria-hidden="true"/><input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder={c.search} aria-label={c.search}/>{search&&<button type="button" className="news-search-clear" onClick={()=>setSearch("")}><i className="bi bi-x-lg" aria-hidden="true"/></button>}</div><div className="news-filters">{[c.all,c.category].map(x=><button type="button" key={x} className={active===x?"active":""} onClick={()=>setActive(x)} aria-pressed={active===x}>{x}</button>)}</div></div><div className="news-results-info"><span><strong>{filtered.length}</strong> {c.count}</span>{(search||active!==c.all)&&<button type="button" onClick={reset}>{c.reset}<i className="bi bi-arrow-counterclockwise" aria-hidden="true"/></button>}</div>
  {loading?<div className="news-empty-state"><div className="news-empty-icon"><i className="bi bi-arrow-repeat" aria-hidden="true"/></div><h3>{c.latest}</h3><p>{c.loading}</p></div>:error?<div className="news-empty-state"><div className="news-empty-icon"><i className="bi bi-exclamation-circle" aria-hidden="true"/></div><h3>{c.empty}</h3><p>{error}</p><button type="button" onClick={reset} className="aapi-primary-button">{c.show}<i className="bi bi-arrow-left" aria-hidden="true"/></button></div>:filtered.length?<div className="row g-4">{filtered.map(item=><div className="col-xl-4 col-lg-6 col-md-6" key={item.id}><article className="news-page-card"><div className="news-page-card-visual">{item.image?<img src={item.image} alt={item.title} loading="lazy"/>:<><div className="news-card-pattern"/><div className="news-page-icon"><i className="bi bi-newspaper" aria-hidden="true"/></div></>}<span className="news-page-category">{item.category}</span><div className="news-page-date"><i className="bi bi-calendar3" aria-hidden="true"/>{formatDate(item.date)}</div></div><div className="news-page-card-content"><div className="news-card-small-meta"><span><i className="bi bi-newspaper" aria-hidden="true"/>{item.category}</span></div><h3>{item.title}</h3><p>{item.excerpt}</p><Link to={`/news/${item.id}`} className="news-read-more">{c.more}<i className="bi bi-arrow-left" aria-hidden="true"/></Link></div></article></div>)}</div>:<div className="news-empty-state"><div className="news-empty-icon"><i className="bi bi-search" aria-hidden="true"/></div><h3>{c.empty}</h3><p>{c.emptyText}</p><button type="button" onClick={reset} className="aapi-primary-button">{c.show}<i className="bi bi-arrow-left" aria-hidden="true"/></button></div>}</div></section>
  <section className="news-page-cta"><div className="container"><div className="news-page-cta-inner"><div className="news-cta-icon"><i className="bi bi-bell" aria-hidden="true"/></div><div className="news-cta-content"><span>{c.stay}</span><h2>{c.cta}</h2><p>{c.ctaText}</p></div></div></div></section></>;
}
export default NewsPage;
